/**
 * generated by Xtext 2.12.0
 */
package co.edu.uniandes.angularJsDsl.validation;

import co.edu.uniandes.angularJsDsl.validation.AbstractAngularJSDSLValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class AngularJSDSLValidator extends AbstractAngularJSDSLValidator {
}
