/*
 * generated by Xtext 2.12.0
 */
package co.edu.uniandes.angularJsDsl.ide.contentassist.antlr;

import co.edu.uniandes.angularJsDsl.ide.contentassist.antlr.internal.InternalAngularJSDSLParser;
import co.edu.uniandes.angularJsDsl.services.AngularJSDSLGrammarAccess;
import com.google.inject.Inject;
import java.util.HashMap;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class AngularJSDSLParser extends AbstractContentAssistParser {

	@Inject
	private AngularJSDSLGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalAngularJSDSLParser createParser() {
		InternalAngularJSDSLParser result = new InternalAngularJSDSLParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getObjetoJavaScriptAccess().getAlternatives(), "rule__ObjetoJavaScript__Alternatives");
					put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
					put(grammarAccess.getEBooleanAccess().getAlternatives(), "rule__EBoolean__Alternatives");
					put(grammarAccess.getAngularJSAppAccess().getGroup(), "rule__AngularJSApp__Group__0");
					put(grammarAccess.getAngularJSAppAccess().getGroup_4(), "rule__AngularJSApp__Group_4__0");
					put(grammarAccess.getAngularJSAppAccess().getGroup_4_3(), "rule__AngularJSApp__Group_4_3__0");
					put(grammarAccess.getAngularJSAppAccess().getGroup_5(), "rule__AngularJSApp__Group_5__0");
					put(grammarAccess.getAngularJSAppAccess().getGroup_5_3(), "rule__AngularJSApp__Group_5_3__0");
					put(grammarAccess.getAngularJSAppAccess().getGroup_6(), "rule__AngularJSApp__Group_6__0");
					put(grammarAccess.getAngularJSAppAccess().getGroup_6_3(), "rule__AngularJSApp__Group_6_3__0");
					put(grammarAccess.getTemplateAccess().getGroup(), "rule__Template__Group__0");
					put(grammarAccess.getTemplateAccess().getGroup_4(), "rule__Template__Group_4__0");
					put(grammarAccess.getTemplateAccess().getGroup_5(), "rule__Template__Group_5__0");
					put(grammarAccess.getTemplateAccess().getGroup_5_3(), "rule__Template__Group_5_3__0");
					put(grammarAccess.getTemplateAccess().getGroup_6(), "rule__Template__Group_6__0");
					put(grammarAccess.getTemplateAccess().getGroup_6_3(), "rule__Template__Group_6_3__0");
					put(grammarAccess.getModuleAccess().getGroup(), "rule__Module__Group__0");
					put(grammarAccess.getModuleAccess().getGroup_4(), "rule__Module__Group_4__0");
					put(grammarAccess.getModuleAccess().getGroup_4_3(), "rule__Module__Group_4_3__0");
					put(grammarAccess.getModuleAccess().getGroup_5(), "rule__Module__Group_5__0");
					put(grammarAccess.getModuleAccess().getGroup_5_3(), "rule__Module__Group_5_3__0");
					put(grammarAccess.getModuleAccess().getGroup_6(), "rule__Module__Group_6__0");
					put(grammarAccess.getModuleAccess().getGroup_6_3(), "rule__Module__Group_6_3__0");
					put(grammarAccess.getModuleAccess().getGroup_7(), "rule__Module__Group_7__0");
					put(grammarAccess.getModuleAccess().getGroup_7_3(), "rule__Module__Group_7_3__0");
					put(grammarAccess.getParametroAccess().getGroup(), "rule__Parametro__Group__0");
					put(grammarAccess.getParametroAccess().getGroup_4(), "rule__Parametro__Group_4__0");
					put(grammarAccess.getSetenciaHTMLAccess().getGroup(), "rule__SetenciaHTML__Group__0");
					put(grammarAccess.getSetenciaHTMLAccess().getGroup_5(), "rule__SetenciaHTML__Group_5__0");
					put(grammarAccess.getSetenciaHTMLAccess().getGroup_5_3(), "rule__SetenciaHTML__Group_5_3__0");
					put(grammarAccess.getSetenciaHTMLAccess().getGroup_6(), "rule__SetenciaHTML__Group_6__0");
					put(grammarAccess.getSetenciaHTMLAccess().getGroup_6_3(), "rule__SetenciaHTML__Group_6_3__0");
					put(grammarAccess.getSetenciaHTMLAccess().getGroup_7(), "rule__SetenciaHTML__Group_7__0");
					put(grammarAccess.getSetenciaHTMLAccess().getGroup_7_3(), "rule__SetenciaHTML__Group_7_3__0");
					put(grammarAccess.getSetenciaHTMLAccess().getGroup_8(), "rule__SetenciaHTML__Group_8__0");
					put(grammarAccess.getSetenciaHTMLAccess().getGroup_8_3(), "rule__SetenciaHTML__Group_8_3__0");
					put(grammarAccess.getDirectivaAccess().getGroup(), "rule__Directiva__Group__0");
					put(grammarAccess.getPropiedadAccess().getGroup(), "rule__Propiedad__Group__0");
					put(grammarAccess.getPropiedadAccess().getGroup_4(), "rule__Propiedad__Group_4__0");
					put(grammarAccess.getCurlyBracesAccess().getGroup(), "rule__CurlyBraces__Group__0");
					put(grammarAccess.getCurlyBracesAccess().getGroup_4(), "rule__CurlyBraces__Group_4__0");
					put(grammarAccess.getCurlyBracesAccess().getGroup_4_3(), "rule__CurlyBraces__Group_4_3__0");
					put(grammarAccess.getExpresionAccess().getGroup(), "rule__Expresion__Group__0");
					put(grammarAccess.getExpresionAccess().getGroup_3(), "rule__Expresion__Group_3__0");
					put(grammarAccess.getExpresionAccess().getGroup_4(), "rule__Expresion__Group_4__0");
					put(grammarAccess.getFiltroAccess().getGroup(), "rule__Filtro__Group__0");
					put(grammarAccess.getFiltroAccess().getGroup_4(), "rule__Filtro__Group_4__0");
					put(grammarAccess.getReferenciaAccess().getGroup(), "rule__Referencia__Group__0");
					put(grammarAccess.getVariableAccess().getGroup(), "rule__Variable__Group__0");
					put(grammarAccess.getVariableAccess().getGroup_4(), "rule__Variable__Group_4__0");
					put(grammarAccess.getFuncionAccess().getGroup(), "rule__Funcion__Group__0");
					put(grammarAccess.getFuncionAccess().getGroup_5(), "rule__Funcion__Group_5__0");
					put(grammarAccess.getFuncionAccess().getGroup_6(), "rule__Funcion__Group_6__0");
					put(grammarAccess.getFuncionAccess().getGroup_6_3(), "rule__Funcion__Group_6_3__0");
					put(grammarAccess.getFuncionAccess().getGroup_7(), "rule__Funcion__Group_7__0");
					put(grammarAccess.getFuncionAccess().getGroup_7_3(), "rule__Funcion__Group_7_3__0");
					put(grammarAccess.getFuncionAccess().getGroup_8(), "rule__Funcion__Group_8__0");
					put(grammarAccess.getFuncionAccess().getGroup_8_3(), "rule__Funcion__Group_8_3__0");
					put(grammarAccess.getControllerAccess().getGroup(), "rule__Controller__Group__0");
					put(grammarAccess.getControllerAccess().getGroup_4(), "rule__Controller__Group_4__0");
					put(grammarAccess.getControllerAccess().getGroup_5(), "rule__Controller__Group_5__0");
					put(grammarAccess.getControllerAccess().getGroup_5_3(), "rule__Controller__Group_5_3__0");
					put(grammarAccess.getControllerAccess().getGroup_6(), "rule__Controller__Group_6__0");
					put(grammarAccess.getControllerAccess().getGroup_6_3(), "rule__Controller__Group_6_3__0");
					put(grammarAccess.getControllerAccess().getGroup_7(), "rule__Controller__Group_7__0");
					put(grammarAccess.getControllerAccess().getGroup_7_3(), "rule__Controller__Group_7_3__0");
					put(grammarAccess.getControllerAccess().getGroup_8(), "rule__Controller__Group_8__0");
					put(grammarAccess.getControllerAccess().getGroup_8_3(), "rule__Controller__Group_8_3__0");
					put(grammarAccess.getServiceAccess().getGroup(), "rule__Service__Group__0");
					put(grammarAccess.getServiceAccess().getGroup_5(), "rule__Service__Group_5__0");
					put(grammarAccess.getServiceAccess().getGroup_5_3(), "rule__Service__Group_5_3__0");
					put(grammarAccess.getAngularJSAppAccess().getNameAssignment_2(), "rule__AngularJSApp__NameAssignment_2");
					put(grammarAccess.getAngularJSAppAccess().getTemplatesAssignment_4_2(), "rule__AngularJSApp__TemplatesAssignment_4_2");
					put(grammarAccess.getAngularJSAppAccess().getTemplatesAssignment_4_3_1(), "rule__AngularJSApp__TemplatesAssignment_4_3_1");
					put(grammarAccess.getAngularJSAppAccess().getModulesAssignment_5_2(), "rule__AngularJSApp__ModulesAssignment_5_2");
					put(grammarAccess.getAngularJSAppAccess().getModulesAssignment_5_3_1(), "rule__AngularJSApp__ModulesAssignment_5_3_1");
					put(grammarAccess.getAngularJSAppAccess().getParametrosAssignment_6_2(), "rule__AngularJSApp__ParametrosAssignment_6_2");
					put(grammarAccess.getAngularJSAppAccess().getParametrosAssignment_6_3_1(), "rule__AngularJSApp__ParametrosAssignment_6_3_1");
					put(grammarAccess.getTemplateAccess().getNameAssignment_2(), "rule__Template__NameAssignment_2");
					put(grammarAccess.getTemplateAccess().getRutaArchivoAssignment_4_1(), "rule__Template__RutaArchivoAssignment_4_1");
					put(grammarAccess.getTemplateAccess().getSetenciahtmlAssignment_5_2(), "rule__Template__SetenciahtmlAssignment_5_2");
					put(grammarAccess.getTemplateAccess().getSetenciahtmlAssignment_5_3_1(), "rule__Template__SetenciahtmlAssignment_5_3_1");
					put(grammarAccess.getTemplateAccess().getDirectivaAssignment_6_2(), "rule__Template__DirectivaAssignment_6_2");
					put(grammarAccess.getTemplateAccess().getDirectivaAssignment_6_3_1(), "rule__Template__DirectivaAssignment_6_3_1");
					put(grammarAccess.getModuleAccess().getNameAssignment_2(), "rule__Module__NameAssignment_2");
					put(grammarAccess.getModuleAccess().getModulesAssignment_4_2(), "rule__Module__ModulesAssignment_4_2");
					put(grammarAccess.getModuleAccess().getModulesAssignment_4_3_1(), "rule__Module__ModulesAssignment_4_3_1");
					put(grammarAccess.getModuleAccess().getControllerAssignment_5_2(), "rule__Module__ControllerAssignment_5_2");
					put(grammarAccess.getModuleAccess().getControllerAssignment_5_3_1(), "rule__Module__ControllerAssignment_5_3_1");
					put(grammarAccess.getModuleAccess().getServicesAssignment_6_2(), "rule__Module__ServicesAssignment_6_2");
					put(grammarAccess.getModuleAccess().getServicesAssignment_6_3_1(), "rule__Module__ServicesAssignment_6_3_1");
					put(grammarAccess.getModuleAccess().getParametrosAssignment_7_2(), "rule__Module__ParametrosAssignment_7_2");
					put(grammarAccess.getModuleAccess().getParametrosAssignment_7_3_1(), "rule__Module__ParametrosAssignment_7_3_1");
					put(grammarAccess.getParametroAccess().getNameAssignment_2(), "rule__Parametro__NameAssignment_2");
					put(grammarAccess.getParametroAccess().getServicesAssignment_4_1(), "rule__Parametro__ServicesAssignment_4_1");
					put(grammarAccess.getSetenciaHTMLAccess().getSelfClosingAssignment_1(), "rule__SetenciaHTML__SelfClosingAssignment_1");
					put(grammarAccess.getSetenciaHTMLAccess().getNameAssignment_3(), "rule__SetenciaHTML__NameAssignment_3");
					put(grammarAccess.getSetenciaHTMLAccess().getSetenciahtmlAssignment_5_2(), "rule__SetenciaHTML__SetenciahtmlAssignment_5_2");
					put(grammarAccess.getSetenciaHTMLAccess().getSetenciahtmlAssignment_5_3_1(), "rule__SetenciaHTML__SetenciahtmlAssignment_5_3_1");
					put(grammarAccess.getSetenciaHTMLAccess().getDirectivasAssignment_6_2(), "rule__SetenciaHTML__DirectivasAssignment_6_2");
					put(grammarAccess.getSetenciaHTMLAccess().getDirectivasAssignment_6_3_1(), "rule__SetenciaHTML__DirectivasAssignment_6_3_1");
					put(grammarAccess.getSetenciaHTMLAccess().getPropiedadesAssignment_7_2(), "rule__SetenciaHTML__PropiedadesAssignment_7_2");
					put(grammarAccess.getSetenciaHTMLAccess().getPropiedadesAssignment_7_3_1(), "rule__SetenciaHTML__PropiedadesAssignment_7_3_1");
					put(grammarAccess.getSetenciaHTMLAccess().getCurlybracesAssignment_8_2(), "rule__SetenciaHTML__CurlybracesAssignment_8_2");
					put(grammarAccess.getSetenciaHTMLAccess().getCurlybracesAssignment_8_3_1(), "rule__SetenciaHTML__CurlybracesAssignment_8_3_1");
					put(grammarAccess.getDirectivaAccess().getNameAssignment_1(), "rule__Directiva__NameAssignment_1");
					put(grammarAccess.getDirectivaAccess().getReferenciaAssignment_4(), "rule__Directiva__ReferenciaAssignment_4");
					put(grammarAccess.getPropiedadAccess().getNameAssignment_2(), "rule__Propiedad__NameAssignment_2");
					put(grammarAccess.getPropiedadAccess().getValorAssignment_4_1(), "rule__Propiedad__ValorAssignment_4_1");
					put(grammarAccess.getCurlyBracesAccess().getExpresionAssignment_3(), "rule__CurlyBraces__ExpresionAssignment_3");
					put(grammarAccess.getCurlyBracesAccess().getFiltroAssignment_4_2(), "rule__CurlyBraces__FiltroAssignment_4_2");
					put(grammarAccess.getCurlyBracesAccess().getFiltroAssignment_4_3_1(), "rule__CurlyBraces__FiltroAssignment_4_3_1");
					put(grammarAccess.getExpresionAccess().getValorAssignment_3_1(), "rule__Expresion__ValorAssignment_3_1");
					put(grammarAccess.getExpresionAccess().getReferenciaAssignment_4_1(), "rule__Expresion__ReferenciaAssignment_4_1");
					put(grammarAccess.getFiltroAccess().getNameAssignment_2(), "rule__Filtro__NameAssignment_2");
					put(grammarAccess.getFiltroAccess().getParametrosAssignment_4_1(), "rule__Filtro__ParametrosAssignment_4_1");
					put(grammarAccess.getReferenciaAccess().getNameAssignment_1(), "rule__Referencia__NameAssignment_1");
					put(grammarAccess.getReferenciaAccess().getObjetoAssignment_4(), "rule__Referencia__ObjetoAssignment_4");
					put(grammarAccess.getVariableAccess().getNameAssignment_2(), "rule__Variable__NameAssignment_2");
					put(grammarAccess.getVariableAccess().getValorAssignment_4_1(), "rule__Variable__ValorAssignment_4_1");
					put(grammarAccess.getFuncionAccess().getTieneRetornoAssignment_1(), "rule__Funcion__TieneRetornoAssignment_1");
					put(grammarAccess.getFuncionAccess().getNameAssignment_3(), "rule__Funcion__NameAssignment_3");
					put(grammarAccess.getFuncionAccess().getBodyAssignment_5_1(), "rule__Funcion__BodyAssignment_5_1");
					put(grammarAccess.getFuncionAccess().getFuncionAssignment_6_2(), "rule__Funcion__FuncionAssignment_6_2");
					put(grammarAccess.getFuncionAccess().getFuncionAssignment_6_3_1(), "rule__Funcion__FuncionAssignment_6_3_1");
					put(grammarAccess.getFuncionAccess().getReferenciaAssignment_7_2(), "rule__Funcion__ReferenciaAssignment_7_2");
					put(grammarAccess.getFuncionAccess().getReferenciaAssignment_7_3_1(), "rule__Funcion__ReferenciaAssignment_7_3_1");
					put(grammarAccess.getFuncionAccess().getParametrosAssignment_8_2(), "rule__Funcion__ParametrosAssignment_8_2");
					put(grammarAccess.getFuncionAccess().getParametrosAssignment_8_3_1(), "rule__Funcion__ParametrosAssignment_8_3_1");
					put(grammarAccess.getControllerAccess().getNameAssignment_2(), "rule__Controller__NameAssignment_2");
					put(grammarAccess.getControllerAccess().getBodyAssignment_4_1(), "rule__Controller__BodyAssignment_4_1");
					put(grammarAccess.getControllerAccess().getServicesAssignment_5_2(), "rule__Controller__ServicesAssignment_5_2");
					put(grammarAccess.getControllerAccess().getServicesAssignment_5_3_1(), "rule__Controller__ServicesAssignment_5_3_1");
					put(grammarAccess.getControllerAccess().getFuncionAssignment_6_2(), "rule__Controller__FuncionAssignment_6_2");
					put(grammarAccess.getControllerAccess().getFuncionAssignment_6_3_1(), "rule__Controller__FuncionAssignment_6_3_1");
					put(grammarAccess.getControllerAccess().getVariableAssignment_7_2(), "rule__Controller__VariableAssignment_7_2");
					put(grammarAccess.getControllerAccess().getVariableAssignment_7_3_1(), "rule__Controller__VariableAssignment_7_3_1");
					put(grammarAccess.getControllerAccess().getParametrosAssignment_8_2(), "rule__Controller__ParametrosAssignment_8_2");
					put(grammarAccess.getControllerAccess().getParametrosAssignment_8_3_1(), "rule__Controller__ParametrosAssignment_8_3_1");
					put(grammarAccess.getServiceAccess().getNameAssignment_1(), "rule__Service__NameAssignment_1");
					put(grammarAccess.getServiceAccess().getParametroAssignment_4(), "rule__Service__ParametroAssignment_4");
					put(grammarAccess.getServiceAccess().getFuncionAssignment_5_2(), "rule__Service__FuncionAssignment_5_2");
					put(grammarAccess.getServiceAccess().getFuncionAssignment_5_3_1(), "rule__Service__FuncionAssignment_5_3_1");
				}
			};
		}
		return nameMappings.get(element);
	}
			
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public AngularJSDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(AngularJSDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
