/*
 * generated by Xtext 2.12.0
 */
package co.edu.uniandes.angular


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class AngularDslStandaloneSetup extends AngularDslStandaloneSetupGenerated {

	def static void doSetup() {
		new AngularDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
