/**
 *
 * $Id$
 */
package Angularjs.validation;

import Angularjs.html.Template;

import Angularjs.mvc.Modelo;
import Angularjs.mvc.Modulo;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link Angularjs.AppAngularJS}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AppAngularJSValidator {
	boolean validate();

	boolean validateModulos(EList<Modulo> value);
	boolean validateTemplate(EList<Template> value);
	boolean validateModelos(EList<Modelo> value);
}
