/**
 * generated by Xtext 2.12.0
 */
package co.edu.uniandes.angular;

import co.edu.uniandes.angular.AngularDslStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class AngularDslStandaloneSetup extends AngularDslStandaloneSetupGenerated {
  public static void doSetup() {
    new AngularDslStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
