/**
 * generated by Xtext 2.12.0
 */
package co.edu.uniandes.angular;

import co.edu.uniandes.angular.AbstractAngularDslRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class AngularDslRuntimeModule extends AbstractAngularDslRuntimeModule {
}
