/**
 *
 * $Id$
 */
package Angularjs.validation;

import Angularjs.Controller;
import Angularjs.Module;
import Angularjs.Parametro;
import Angularjs.Service;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link Angularjs.Module}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ModuleValidator {
	boolean validate();

	boolean validateController(EList<Controller> value);
	boolean validateModules(EList<Module> value);
	boolean validateServices(EList<Service> value);
	boolean validateParametros(EList<Parametro> value);
}
