/**
 *
 * $Id$
 */
package Angularjs.mvc.validation;

import Angularjs.html.Template;

import Angularjs.mvc.Funcion;
import Angularjs.mvc.Modelo;
import Angularjs.mvc.Parametro;
import Angularjs.mvc.Service;
import Angularjs.mvc.Variable;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link Angularjs.mvc.Controller}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ControllerValidator {
	boolean validate();

	boolean validateServices(EList<Service> value);
	boolean validateFuncion(EList<Funcion> value);
	boolean validateVariable(EList<Variable> value);
	boolean validateParametros(EList<Parametro> value);
	boolean validateBody(String value);
	boolean validateTemplate(Template value);
	boolean validateModelo(EList<Modelo> value);
}
