/**
 *
 * $Id$
 */
package Angularjs.mvc.validation;

import Angularjs.mvc.Controller;
import Angularjs.mvc.Modulo;
import Angularjs.mvc.Parametro;
import Angularjs.mvc.Service;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link Angularjs.mvc.Modulo}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ModuloValidator {
	boolean validate();

	boolean validateParametros(EList<Parametro> value);
	boolean validateServices(EList<Service> value);
	boolean validateController(EList<Controller> value);
	boolean validateModulos(EList<Modulo> value);
}
