/**
 * generated by Xtext 2.12.0
 */
package co.edu.uniandes.angular.validation;

import co.edu.uniandes.angular.validation.AbstractAngularDslValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class AngularDslValidator extends AbstractAngularDslValidator {
}
