/*
 * generated by Xtext 2.12.0
 */
package co.edu.uniandes.angular.parser.antlr;

import co.edu.uniandes.angular.parser.antlr.internal.InternalAngularDslParser;
import co.edu.uniandes.angular.services.AngularDslGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class AngularDslParser extends AbstractAntlrParser {

	@Inject
	private AngularDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalAngularDslParser createParser(XtextTokenStream stream) {
		return new InternalAngularDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "AppAngular";
	}

	public AngularDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(AngularDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
