/**
 * generated by Xtext 2.12.0
 */
package co.edu.uniandes.validation;

import co.edu.uniandes.validation.AbstractAngularJsDslValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class AngularJsDslValidator extends AbstractAngularJsDslValidator {
}
