/*
 * generated by Xtext 2.12.0
 */
package co.edu.uniandes.parser.antlr;

import co.edu.uniandes.parser.antlr.internal.InternalAngularJsDslParser;
import co.edu.uniandes.services.AngularJsDslGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class AngularJsDslParser extends AbstractAntlrParser {

	@Inject
	private AngularJsDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalAngularJsDslParser createParser(XtextTokenStream stream) {
		return new InternalAngularJsDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "AngularJSApp";
	}

	public AngularJsDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(AngularJsDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
