/**
 * generated by Xtext 2.12.0
 */
package co.edu.uniandes.angular.ui;

import co.edu.uniandes.angular.ui.AbstractAngularDslUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class AngularDslUiModule extends AbstractAngularDslUiModule {
  public AngularDslUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
