/*
 * generated by Xtext 2.12.0
 */
package co.edu.uniandes.angularJsDsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractAngularJSDSLScopeProvider extends DelegatingScopeProvider {
}
