/**
 *
 * $Id$
 */
package Angularjs.html.validation;

import Angularjs.html.Referencia;

/**
 * A sample validator interface for {@link Angularjs.html.Expresion}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ExpresionValidator {
	boolean validate();

	boolean validateValor(String value);
	boolean validateReferencia(Referencia value);
}
