/**
 *
 * $Id$
 */
package angularjs2angular5.angular.validation;

import angularjs2angular5.angular.Componente;
import angularjs2angular5.angular.Modelo;
import angularjs2angular5.angular.Modulo;
import angularjs2angular5.angular.Service;
import angularjs2angular5.angular.Template;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link angularjs2angular5.angular.AppAngular}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AppAngularValidator {
	boolean validate();

	boolean validateModulos(EList<Modulo> value);

	boolean validateTemplates(EList<Template> value);

	boolean validateModelos(EList<Modelo> value);

	boolean validateName(String value);

	boolean validateServices(EList<Service> value);

	boolean validateComponentes(EList<Componente> value);
}
