/**
 *
 * $Id$
 */
package angularjs2angular5.angular.validation;

import angularjs2angular5.angular.Funcion;
import angularjs2angular5.angular.Modelo;
import angularjs2angular5.angular.Modulo;
import angularjs2angular5.angular.ObjetoAngular;
import angularjs2angular5.angular.Template;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link angularjs2angular5.angular.Componente}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ComponenteValidator {
	boolean validate();

	boolean validateFuncion(Funcion value);

	boolean validateTemplate(Template value);

	boolean validateModelo(EList<Modelo> value);

	boolean validateParametros(EList<ObjetoAngular> value);

	boolean validateModulo(Modulo value);
}
