/**
 *
 * $Id$
 */
package angularjs2angular5.angular.validation;

import angularjs2angular5.angular.CurlyBraces;
import angularjs2angular5.angular.Directiva;
import angularjs2angular5.angular.Propiedad;
import angularjs2angular5.angular.SentenciaHTML;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link angularjs2angular5.angular.SentenciaHTML}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SentenciaHTMLValidator {
	boolean validate();

	boolean validateSentenciashtml(EList<SentenciaHTML> value);

	boolean validateName(String value);

	boolean validatePropiedades(EList<Propiedad> value);

	boolean validateCurlybraces(EList<CurlyBraces> value);

	boolean validateDirectivas(EList<Directiva> value);
}
