/**
 * generated by Xtext 2.12.0
 */
package co.edu.uniandes.angular.formatting2;

import angularjs2angular5.angular.AppAngular;
import angularjs2angular5.angular.Componente;
import angularjs2angular5.angular.Modelo;
import angularjs2angular5.angular.Modulo;
import angularjs2angular5.angular.SentenciaHTML;
import angularjs2angular5.angular.Service;
import angularjs2angular5.angular.Template;
import co.edu.uniandes.angular.services.AngularDslGrammarAccess;
import com.google.inject.Inject;
import java.util.Arrays;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;

@SuppressWarnings("all")
public class AngularDslFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private AngularDslGrammarAccess _angularDslGrammarAccess;
  
  protected void _format(final AppAngular appAngular, @Extension final IFormattableDocument document) {
    EList<Modulo> _modulos = appAngular.getModulos();
    for (final Modulo modulo : _modulos) {
      document.<Modulo>format(modulo);
    }
    EList<Template> _templates = appAngular.getTemplates();
    for (final Template template : _templates) {
      document.<Template>format(template);
    }
    EList<Service> _services = appAngular.getServices();
    for (final Service service : _services) {
      document.<Service>format(service);
    }
    EList<Modelo> _modelos = appAngular.getModelos();
    for (final Modelo modelo : _modelos) {
      document.<Modelo>format(modelo);
    }
    EList<Componente> _componentes = appAngular.getComponentes();
    for (final Componente componente : _componentes) {
      document.<Componente>format(componente);
    }
  }
  
  protected void _format(final Template template, @Extension final IFormattableDocument document) {
    EList<SentenciaHTML> _sentenciashtml = template.getSentenciashtml();
    for (final SentenciaHTML sentenciaHTML : _sentenciashtml) {
      document.<SentenciaHTML>format(sentenciaHTML);
    }
  }
  
  public void format(final Object appAngular, final IFormattableDocument document) {
    if (appAngular instanceof XtextResource) {
      _format((XtextResource)appAngular, document);
      return;
    } else if (appAngular instanceof AppAngular) {
      _format((AppAngular)appAngular, document);
      return;
    } else if (appAngular instanceof Template) {
      _format((Template)appAngular, document);
      return;
    } else if (appAngular instanceof EObject) {
      _format((EObject)appAngular, document);
      return;
    } else if (appAngular == null) {
      _format((Void)null, document);
      return;
    } else if (appAngular != null) {
      _format(appAngular, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(appAngular, document).toString());
    }
  }
}
