/**
 * generated by Xtext 2.12.0
 */
package co.edu.uniandes.angular.ide;

import co.edu.uniandes.angular.ide.AbstractAngularDslIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class AngularDslIdeModule extends AbstractAngularDslIdeModule {
}
