/*
 * generated by Xtext 2.12.0
 */
package co.edu.uniandes.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractAngularJsDslScopeProvider extends DelegatingScopeProvider {
}
