/**
 * generated by Xtext 2.12.0
 */
package co.edu.uniandes.angular.scoping;

import co.edu.uniandes.angular.scoping.AbstractAngularDslScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class AngularDslScopeProvider extends AbstractAngularDslScopeProvider {
}
