/*
 * generated by Xtext 2.12.0
 */
package co.edu.uniandes.angular.ui.tests;

import co.edu.uniandes.angular.AngularDsl.ui.internal.AngularDslActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class AngularDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return AngularDslActivator.getInstance().getInjector("co.edu.uniandes.angular.AngularDsl");
	}

}
