/*
 * generated by Xtext 2.12.0
 */
package co.edu.uniandes.angular.tests

import angularjs2angular5.angular.AppAngular
import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(AngularDslInjectorProvider)
class AngularDslParsingTest {
	@Inject
	ParseHelper<AppAngular> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
		Assert.assertTrue(result.eResource.errors.isEmpty)
	}
}
