/*
 * generated by Xtext 2.12.0
 */
package co.edu.uniandes.angular.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class AngularDslGrammarAccess extends AbstractGrammarElementFinder {
	
	public class AppAngularElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.uniandes.angular.AngularDsl.AppAngular");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cModulosAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final RuleCall cModulosModuloParserRuleCall_0_0 = (RuleCall)cModulosAssignment_0.eContents().get(0);
		private final Assignment cComponentesAssignment_1 = (Assignment)cAlternatives.eContents().get(1);
		private final RuleCall cComponentesComponenteParserRuleCall_1_0 = (RuleCall)cComponentesAssignment_1.eContents().get(0);
		private final Assignment cServicesAssignment_2 = (Assignment)cAlternatives.eContents().get(2);
		private final RuleCall cServicesServiceParserRuleCall_2_0 = (RuleCall)cServicesAssignment_2.eContents().get(0);
		private final Assignment cTemplatesAssignment_3 = (Assignment)cAlternatives.eContents().get(3);
		private final RuleCall cTemplatesTemplateParserRuleCall_3_0 = (RuleCall)cTemplatesAssignment_3.eContents().get(0);
		
		//AppAngular:
		//	modulos+=Modulo | componentes+=Componente | services+=Service | templates+=Template;
		@Override public ParserRule getRule() { return rule; }
		
		//modulos+=Modulo | componentes+=Componente | services+=Service | templates+=Template
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//modulos+=Modulo
		public Assignment getModulosAssignment_0() { return cModulosAssignment_0; }
		
		//Modulo
		public RuleCall getModulosModuloParserRuleCall_0_0() { return cModulosModuloParserRuleCall_0_0; }
		
		//componentes+=Componente
		public Assignment getComponentesAssignment_1() { return cComponentesAssignment_1; }
		
		//Componente
		public RuleCall getComponentesComponenteParserRuleCall_1_0() { return cComponentesComponenteParserRuleCall_1_0; }
		
		//services+=Service
		public Assignment getServicesAssignment_2() { return cServicesAssignment_2; }
		
		//Service
		public RuleCall getServicesServiceParserRuleCall_2_0() { return cServicesServiceParserRuleCall_2_0; }
		
		//templates+=Template
		public Assignment getTemplatesAssignment_3() { return cTemplatesAssignment_3; }
		
		//Template
		public RuleCall getTemplatesTemplateParserRuleCall_3_0() { return cTemplatesTemplateParserRuleCall_3_0; }
	}
	public class ObjetoAngularElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.uniandes.angular.AngularDsl.ObjetoAngular");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cModuloParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cComponenteParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cServiceParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//ObjetoAngular:
		//	Modulo | Componente | Service;
		@Override public ParserRule getRule() { return rule; }
		
		//Modulo | Componente | Service
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Modulo
		public RuleCall getModuloParserRuleCall_0() { return cModuloParserRuleCall_0; }
		
		//Componente
		public RuleCall getComponenteParserRuleCall_1() { return cComponenteParserRuleCall_1; }
		
		//Service
		public RuleCall getServiceParserRuleCall_2() { return cServiceParserRuleCall_2; }
	}
	public class ModuloElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.uniandes.angular.AngularDsl.Modulo");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cModuloAction_0 = (Action)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final RuleCall cCOMILLASTerminalRuleCall_1_0 = (RuleCall)cGroup_1.eContents().get(0);
		private final RuleCall cUSETerminalRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		private final RuleCall cSTRICTTerminalRuleCall_1_2 = (RuleCall)cGroup_1.eContents().get(2);
		private final RuleCall cCOMILLASTerminalRuleCall_1_3 = (RuleCall)cGroup_1.eContents().get(3);
		private final RuleCall cPUNTO_Y_COMATerminalRuleCall_1_4 = (RuleCall)cGroup_1.eContents().get(4);
		private final RuleCall cANGULARTerminalRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		private final RuleCall cPUNTOTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final RuleCall cMODULETerminalRuleCall_4 = (RuleCall)cGroup.eContents().get(4);
		private final RuleCall cPARENTESIS_IZQUIERDOTerminalRuleCall_5 = (RuleCall)cGroup.eContents().get(5);
		private final Assignment cNameAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cNameEStringParserRuleCall_6_0 = (RuleCall)cNameAssignment_6.eContents().get(0);
		private final RuleCall cCOMATerminalRuleCall_7 = (RuleCall)cGroup.eContents().get(7);
		private final RuleCall cPARENTESIS_CUADRADO_IZQUIERDOTerminalRuleCall_8 = (RuleCall)cGroup.eContents().get(8);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Assignment cParametrosAssignment_9_0 = (Assignment)cGroup_9.eContents().get(0);
		private final CrossReference cParametrosObjetoAngularCrossReference_9_0_0 = (CrossReference)cParametrosAssignment_9_0.eContents().get(0);
		private final RuleCall cParametrosObjetoAngularEStringParserRuleCall_9_0_0_1 = (RuleCall)cParametrosObjetoAngularCrossReference_9_0_0.eContents().get(1);
		private final Group cGroup_9_1 = (Group)cGroup_9.eContents().get(1);
		private final RuleCall cCOMATerminalRuleCall_9_1_0 = (RuleCall)cGroup_9_1.eContents().get(0);
		private final Assignment cParametrosAssignment_9_1_1 = (Assignment)cGroup_9_1.eContents().get(1);
		private final CrossReference cParametrosObjetoAngularCrossReference_9_1_1_0 = (CrossReference)cParametrosAssignment_9_1_1.eContents().get(0);
		private final RuleCall cParametrosObjetoAngularEStringParserRuleCall_9_1_1_0_1 = (RuleCall)cParametrosObjetoAngularCrossReference_9_1_1_0.eContents().get(1);
		private final RuleCall cPARENTESIS_CUADRADO_DERECHOTerminalRuleCall_10 = (RuleCall)cGroup.eContents().get(10);
		private final RuleCall cPARENTESIS_DERECHOTerminalRuleCall_11 = (RuleCall)cGroup.eContents().get(11);
		private final RuleCall cPUNTO_Y_COMATerminalRuleCall_12 = (RuleCall)cGroup.eContents().get(12);
		
		//Modulo:
		//	{Modulo} (COMILLAS USE STRICT COMILLAS PUNTO_Y_COMA)? ANGULAR PUNTO MODULE PARENTESIS_IZQUIERDO
		//	name=EString COMA
		//	PARENTESIS_CUADRADO_IZQUIERDO (parametros+=[ObjetoAngular|EString] (COMA parametros+=[ObjetoAngular|EString])*)*
		//	PARENTESIS_CUADRADO_DERECHO
		//	PARENTESIS_DERECHO PUNTO_Y_COMA;
		@Override public ParserRule getRule() { return rule; }
		
		//{Modulo} (COMILLAS USE STRICT COMILLAS PUNTO_Y_COMA)? ANGULAR PUNTO MODULE PARENTESIS_IZQUIERDO name=EString COMA
		//PARENTESIS_CUADRADO_IZQUIERDO (parametros+=[ObjetoAngular|EString] (COMA parametros+=[ObjetoAngular|EString])*)*
		//PARENTESIS_CUADRADO_DERECHO PARENTESIS_DERECHO PUNTO_Y_COMA
		public Group getGroup() { return cGroup; }
		
		//{Modulo}
		public Action getModuloAction_0() { return cModuloAction_0; }
		
		//(COMILLAS USE STRICT COMILLAS PUNTO_Y_COMA)?
		public Group getGroup_1() { return cGroup_1; }
		
		//COMILLAS
		public RuleCall getCOMILLASTerminalRuleCall_1_0() { return cCOMILLASTerminalRuleCall_1_0; }
		
		//USE
		public RuleCall getUSETerminalRuleCall_1_1() { return cUSETerminalRuleCall_1_1; }
		
		//STRICT
		public RuleCall getSTRICTTerminalRuleCall_1_2() { return cSTRICTTerminalRuleCall_1_2; }
		
		//COMILLAS
		public RuleCall getCOMILLASTerminalRuleCall_1_3() { return cCOMILLASTerminalRuleCall_1_3; }
		
		//PUNTO_Y_COMA
		public RuleCall getPUNTO_Y_COMATerminalRuleCall_1_4() { return cPUNTO_Y_COMATerminalRuleCall_1_4; }
		
		//ANGULAR
		public RuleCall getANGULARTerminalRuleCall_2() { return cANGULARTerminalRuleCall_2; }
		
		//PUNTO
		public RuleCall getPUNTOTerminalRuleCall_3() { return cPUNTOTerminalRuleCall_3; }
		
		//MODULE
		public RuleCall getMODULETerminalRuleCall_4() { return cMODULETerminalRuleCall_4; }
		
		//PARENTESIS_IZQUIERDO
		public RuleCall getPARENTESIS_IZQUIERDOTerminalRuleCall_5() { return cPARENTESIS_IZQUIERDOTerminalRuleCall_5; }
		
		//name=EString
		public Assignment getNameAssignment_6() { return cNameAssignment_6; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_6_0() { return cNameEStringParserRuleCall_6_0; }
		
		//COMA
		public RuleCall getCOMATerminalRuleCall_7() { return cCOMATerminalRuleCall_7; }
		
		//PARENTESIS_CUADRADO_IZQUIERDO
		public RuleCall getPARENTESIS_CUADRADO_IZQUIERDOTerminalRuleCall_8() { return cPARENTESIS_CUADRADO_IZQUIERDOTerminalRuleCall_8; }
		
		//(parametros+=[ObjetoAngular|EString] (COMA parametros+=[ObjetoAngular|EString])*)*
		public Group getGroup_9() { return cGroup_9; }
		
		//parametros+=[ObjetoAngular|EString]
		public Assignment getParametrosAssignment_9_0() { return cParametrosAssignment_9_0; }
		
		//[ObjetoAngular|EString]
		public CrossReference getParametrosObjetoAngularCrossReference_9_0_0() { return cParametrosObjetoAngularCrossReference_9_0_0; }
		
		//EString
		public RuleCall getParametrosObjetoAngularEStringParserRuleCall_9_0_0_1() { return cParametrosObjetoAngularEStringParserRuleCall_9_0_0_1; }
		
		//(COMA parametros+=[ObjetoAngular|EString])*
		public Group getGroup_9_1() { return cGroup_9_1; }
		
		//COMA
		public RuleCall getCOMATerminalRuleCall_9_1_0() { return cCOMATerminalRuleCall_9_1_0; }
		
		//parametros+=[ObjetoAngular|EString]
		public Assignment getParametrosAssignment_9_1_1() { return cParametrosAssignment_9_1_1; }
		
		//[ObjetoAngular|EString]
		public CrossReference getParametrosObjetoAngularCrossReference_9_1_1_0() { return cParametrosObjetoAngularCrossReference_9_1_1_0; }
		
		//EString
		public RuleCall getParametrosObjetoAngularEStringParserRuleCall_9_1_1_0_1() { return cParametrosObjetoAngularEStringParserRuleCall_9_1_1_0_1; }
		
		//PARENTESIS_CUADRADO_DERECHO
		public RuleCall getPARENTESIS_CUADRADO_DERECHOTerminalRuleCall_10() { return cPARENTESIS_CUADRADO_DERECHOTerminalRuleCall_10; }
		
		//PARENTESIS_DERECHO
		public RuleCall getPARENTESIS_DERECHOTerminalRuleCall_11() { return cPARENTESIS_DERECHOTerminalRuleCall_11; }
		
		//PUNTO_Y_COMA
		public RuleCall getPUNTO_Y_COMATerminalRuleCall_12() { return cPUNTO_Y_COMATerminalRuleCall_12; }
	}
	public class ServiceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.uniandes.angular.AngularDsl.Service");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cServiceAction_0 = (Action)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final RuleCall cCOMILLASTerminalRuleCall_1_0 = (RuleCall)cGroup_1.eContents().get(0);
		private final RuleCall cUSETerminalRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		private final RuleCall cSTRICTTerminalRuleCall_1_2 = (RuleCall)cGroup_1.eContents().get(2);
		private final RuleCall cCOMILLASTerminalRuleCall_1_3 = (RuleCall)cGroup_1.eContents().get(3);
		private final RuleCall cPUNTO_Y_COMATerminalRuleCall_1_4 = (RuleCall)cGroup_1.eContents().get(4);
		private final RuleCall cANGULARTerminalRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		private final RuleCall cPUNTOTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final RuleCall cMODULETerminalRuleCall_4 = (RuleCall)cGroup.eContents().get(4);
		private final RuleCall cPARENTESIS_IZQUIERDOTerminalRuleCall_5 = (RuleCall)cGroup.eContents().get(5);
		private final Assignment cModuloAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final CrossReference cModuloModuloCrossReference_6_0 = (CrossReference)cModuloAssignment_6.eContents().get(0);
		private final RuleCall cModuloModuloEStringParserRuleCall_6_0_1 = (RuleCall)cModuloModuloCrossReference_6_0.eContents().get(1);
		private final RuleCall cPARENTESIS_DERECHOTerminalRuleCall_7 = (RuleCall)cGroup.eContents().get(7);
		private final RuleCall cPUNTOTerminalRuleCall_8 = (RuleCall)cGroup.eContents().get(8);
		private final Keyword cFactoryKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final RuleCall cPARENTESIS_IZQUIERDOTerminalRuleCall_10 = (RuleCall)cGroup.eContents().get(10);
		private final Assignment cNameAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final RuleCall cNameEStringParserRuleCall_11_0 = (RuleCall)cNameAssignment_11.eContents().get(0);
		private final RuleCall cCOMATerminalRuleCall_12 = (RuleCall)cGroup.eContents().get(12);
		private final RuleCall cPARENTESIS_CUADRADO_IZQUIERDOTerminalRuleCall_13 = (RuleCall)cGroup.eContents().get(13);
		private final Group cGroup_14 = (Group)cGroup.eContents().get(14);
		private final Assignment cParametrosAssignment_14_0 = (Assignment)cGroup_14.eContents().get(0);
		private final CrossReference cParametrosObjetoAngularCrossReference_14_0_0 = (CrossReference)cParametrosAssignment_14_0.eContents().get(0);
		private final RuleCall cParametrosObjetoAngularEStringParserRuleCall_14_0_0_1 = (RuleCall)cParametrosObjetoAngularCrossReference_14_0_0.eContents().get(1);
		private final Group cGroup_14_1 = (Group)cGroup_14.eContents().get(1);
		private final RuleCall cCOMATerminalRuleCall_14_1_0 = (RuleCall)cGroup_14_1.eContents().get(0);
		private final Assignment cParametrosAssignment_14_1_1 = (Assignment)cGroup_14_1.eContents().get(1);
		private final CrossReference cParametrosObjetoAngularCrossReference_14_1_1_0 = (CrossReference)cParametrosAssignment_14_1_1.eContents().get(0);
		private final RuleCall cParametrosObjetoAngularEStringParserRuleCall_14_1_1_0_1 = (RuleCall)cParametrosObjetoAngularCrossReference_14_1_1_0.eContents().get(1);
		private final RuleCall cCOMATerminalRuleCall_15 = (RuleCall)cGroup.eContents().get(15);
		private final Assignment cFuncionAssignment_16 = (Assignment)cGroup.eContents().get(16);
		private final RuleCall cFuncionFuncionParserRuleCall_16_0 = (RuleCall)cFuncionAssignment_16.eContents().get(0);
		private final RuleCall cPARENTESIS_CUADRADO_DERECHOTerminalRuleCall_17 = (RuleCall)cGroup.eContents().get(17);
		private final RuleCall cPARENTESIS_DERECHOTerminalRuleCall_18 = (RuleCall)cGroup.eContents().get(18);
		private final RuleCall cPUNTO_Y_COMATerminalRuleCall_19 = (RuleCall)cGroup.eContents().get(19);
		
		//Service:
		//	{Service} (COMILLAS USE STRICT COMILLAS PUNTO_Y_COMA)? ANGULAR PUNTO MODULE PARENTESIS_IZQUIERDO
		//	modulo=[Modulo|EString] PARENTESIS_DERECHO PUNTO 'factory' PARENTESIS_IZQUIERDO name=EString COMA
		//	PARENTESIS_CUADRADO_IZQUIERDO (parametros+=[ObjetoAngular|EString] (COMA parametros+=[ObjetoAngular|EString])*)* COMA
		//	funcion=Funcion
		//	PARENTESIS_CUADRADO_DERECHO
		//	PARENTESIS_DERECHO PUNTO_Y_COMA;
		@Override public ParserRule getRule() { return rule; }
		
		//{Service} (COMILLAS USE STRICT COMILLAS PUNTO_Y_COMA)? ANGULAR PUNTO MODULE PARENTESIS_IZQUIERDO modulo=[Modulo|EString]
		//PARENTESIS_DERECHO PUNTO 'factory' PARENTESIS_IZQUIERDO name=EString COMA PARENTESIS_CUADRADO_IZQUIERDO
		//(parametros+=[ObjetoAngular|EString] (COMA parametros+=[ObjetoAngular|EString])*)* COMA funcion=Funcion
		//PARENTESIS_CUADRADO_DERECHO PARENTESIS_DERECHO PUNTO_Y_COMA
		public Group getGroup() { return cGroup; }
		
		//{Service}
		public Action getServiceAction_0() { return cServiceAction_0; }
		
		//(COMILLAS USE STRICT COMILLAS PUNTO_Y_COMA)?
		public Group getGroup_1() { return cGroup_1; }
		
		//COMILLAS
		public RuleCall getCOMILLASTerminalRuleCall_1_0() { return cCOMILLASTerminalRuleCall_1_0; }
		
		//USE
		public RuleCall getUSETerminalRuleCall_1_1() { return cUSETerminalRuleCall_1_1; }
		
		//STRICT
		public RuleCall getSTRICTTerminalRuleCall_1_2() { return cSTRICTTerminalRuleCall_1_2; }
		
		//COMILLAS
		public RuleCall getCOMILLASTerminalRuleCall_1_3() { return cCOMILLASTerminalRuleCall_1_3; }
		
		//PUNTO_Y_COMA
		public RuleCall getPUNTO_Y_COMATerminalRuleCall_1_4() { return cPUNTO_Y_COMATerminalRuleCall_1_4; }
		
		//ANGULAR
		public RuleCall getANGULARTerminalRuleCall_2() { return cANGULARTerminalRuleCall_2; }
		
		//PUNTO
		public RuleCall getPUNTOTerminalRuleCall_3() { return cPUNTOTerminalRuleCall_3; }
		
		//MODULE
		public RuleCall getMODULETerminalRuleCall_4() { return cMODULETerminalRuleCall_4; }
		
		//PARENTESIS_IZQUIERDO
		public RuleCall getPARENTESIS_IZQUIERDOTerminalRuleCall_5() { return cPARENTESIS_IZQUIERDOTerminalRuleCall_5; }
		
		//modulo=[Modulo|EString]
		public Assignment getModuloAssignment_6() { return cModuloAssignment_6; }
		
		//[Modulo|EString]
		public CrossReference getModuloModuloCrossReference_6_0() { return cModuloModuloCrossReference_6_0; }
		
		//EString
		public RuleCall getModuloModuloEStringParserRuleCall_6_0_1() { return cModuloModuloEStringParserRuleCall_6_0_1; }
		
		//PARENTESIS_DERECHO
		public RuleCall getPARENTESIS_DERECHOTerminalRuleCall_7() { return cPARENTESIS_DERECHOTerminalRuleCall_7; }
		
		//PUNTO
		public RuleCall getPUNTOTerminalRuleCall_8() { return cPUNTOTerminalRuleCall_8; }
		
		//'factory'
		public Keyword getFactoryKeyword_9() { return cFactoryKeyword_9; }
		
		//PARENTESIS_IZQUIERDO
		public RuleCall getPARENTESIS_IZQUIERDOTerminalRuleCall_10() { return cPARENTESIS_IZQUIERDOTerminalRuleCall_10; }
		
		//name=EString
		public Assignment getNameAssignment_11() { return cNameAssignment_11; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_11_0() { return cNameEStringParserRuleCall_11_0; }
		
		//COMA
		public RuleCall getCOMATerminalRuleCall_12() { return cCOMATerminalRuleCall_12; }
		
		//PARENTESIS_CUADRADO_IZQUIERDO
		public RuleCall getPARENTESIS_CUADRADO_IZQUIERDOTerminalRuleCall_13() { return cPARENTESIS_CUADRADO_IZQUIERDOTerminalRuleCall_13; }
		
		//(parametros+=[ObjetoAngular|EString] (COMA parametros+=[ObjetoAngular|EString])*)*
		public Group getGroup_14() { return cGroup_14; }
		
		//parametros+=[ObjetoAngular|EString]
		public Assignment getParametrosAssignment_14_0() { return cParametrosAssignment_14_0; }
		
		//[ObjetoAngular|EString]
		public CrossReference getParametrosObjetoAngularCrossReference_14_0_0() { return cParametrosObjetoAngularCrossReference_14_0_0; }
		
		//EString
		public RuleCall getParametrosObjetoAngularEStringParserRuleCall_14_0_0_1() { return cParametrosObjetoAngularEStringParserRuleCall_14_0_0_1; }
		
		//(COMA parametros+=[ObjetoAngular|EString])*
		public Group getGroup_14_1() { return cGroup_14_1; }
		
		//COMA
		public RuleCall getCOMATerminalRuleCall_14_1_0() { return cCOMATerminalRuleCall_14_1_0; }
		
		//parametros+=[ObjetoAngular|EString]
		public Assignment getParametrosAssignment_14_1_1() { return cParametrosAssignment_14_1_1; }
		
		//[ObjetoAngular|EString]
		public CrossReference getParametrosObjetoAngularCrossReference_14_1_1_0() { return cParametrosObjetoAngularCrossReference_14_1_1_0; }
		
		//EString
		public RuleCall getParametrosObjetoAngularEStringParserRuleCall_14_1_1_0_1() { return cParametrosObjetoAngularEStringParserRuleCall_14_1_1_0_1; }
		
		//COMA
		public RuleCall getCOMATerminalRuleCall_15() { return cCOMATerminalRuleCall_15; }
		
		//funcion=Funcion
		public Assignment getFuncionAssignment_16() { return cFuncionAssignment_16; }
		
		//Funcion
		public RuleCall getFuncionFuncionParserRuleCall_16_0() { return cFuncionFuncionParserRuleCall_16_0; }
		
		//PARENTESIS_CUADRADO_DERECHO
		public RuleCall getPARENTESIS_CUADRADO_DERECHOTerminalRuleCall_17() { return cPARENTESIS_CUADRADO_DERECHOTerminalRuleCall_17; }
		
		//PARENTESIS_DERECHO
		public RuleCall getPARENTESIS_DERECHOTerminalRuleCall_18() { return cPARENTESIS_DERECHOTerminalRuleCall_18; }
		
		//PUNTO_Y_COMA
		public RuleCall getPUNTO_Y_COMATerminalRuleCall_19() { return cPUNTO_Y_COMATerminalRuleCall_19; }
	}
	public class ComponenteElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.uniandes.angular.AngularDsl.Componente");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cComponenteAction_0 = (Action)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final RuleCall cCOMILLASTerminalRuleCall_1_0 = (RuleCall)cGroup_1.eContents().get(0);
		private final RuleCall cUSETerminalRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		private final RuleCall cSTRICTTerminalRuleCall_1_2 = (RuleCall)cGroup_1.eContents().get(2);
		private final RuleCall cCOMILLASTerminalRuleCall_1_3 = (RuleCall)cGroup_1.eContents().get(3);
		private final RuleCall cPUNTO_Y_COMATerminalRuleCall_1_4 = (RuleCall)cGroup_1.eContents().get(4);
		private final RuleCall cANGULARTerminalRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		private final RuleCall cPUNTOTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final RuleCall cMODULETerminalRuleCall_4 = (RuleCall)cGroup.eContents().get(4);
		private final RuleCall cPARENTESIS_IZQUIERDOTerminalRuleCall_5 = (RuleCall)cGroup.eContents().get(5);
		private final Assignment cModuloAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final CrossReference cModuloModuloCrossReference_6_0 = (CrossReference)cModuloAssignment_6.eContents().get(0);
		private final RuleCall cModuloModuloEStringParserRuleCall_6_0_1 = (RuleCall)cModuloModuloCrossReference_6_0.eContents().get(1);
		private final RuleCall cPARENTESIS_DERECHOTerminalRuleCall_7 = (RuleCall)cGroup.eContents().get(7);
		private final RuleCall cPUNTOTerminalRuleCall_8 = (RuleCall)cGroup.eContents().get(8);
		private final RuleCall cCOMPONENTTerminalRuleCall_9 = (RuleCall)cGroup.eContents().get(9);
		private final RuleCall cPARENTESIS_IZQUIERDOTerminalRuleCall_10 = (RuleCall)cGroup.eContents().get(10);
		private final Assignment cNameAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final RuleCall cNameEStringParserRuleCall_11_0 = (RuleCall)cNameAssignment_11.eContents().get(0);
		private final RuleCall cCOMATerminalRuleCall_12 = (RuleCall)cGroup.eContents().get(12);
		private final RuleCall cLLAVE_IZQUIERDATerminalRuleCall_13 = (RuleCall)cGroup.eContents().get(13);
		private final RuleCall cTEMPLATE_URLTerminalRuleCall_14 = (RuleCall)cGroup.eContents().get(14);
		private final RuleCall cDOS_PUNTOSTerminalRuleCall_15 = (RuleCall)cGroup.eContents().get(15);
		private final Assignment cTemplateAssignment_16 = (Assignment)cGroup.eContents().get(16);
		private final CrossReference cTemplateTemplateCrossReference_16_0 = (CrossReference)cTemplateAssignment_16.eContents().get(0);
		private final RuleCall cTemplateTemplateEStringParserRuleCall_16_0_1 = (RuleCall)cTemplateTemplateCrossReference_16_0.eContents().get(1);
		private final RuleCall cCOMATerminalRuleCall_17 = (RuleCall)cGroup.eContents().get(17);
		private final RuleCall cCONTROLLERTerminalRuleCall_18 = (RuleCall)cGroup.eContents().get(18);
		private final RuleCall cDOS_PUNTOSTerminalRuleCall_19 = (RuleCall)cGroup.eContents().get(19);
		private final RuleCall cPARENTESIS_CUADRADO_IZQUIERDOTerminalRuleCall_20 = (RuleCall)cGroup.eContents().get(20);
		private final Group cGroup_21 = (Group)cGroup.eContents().get(21);
		private final Assignment cParametrosAssignment_21_0 = (Assignment)cGroup_21.eContents().get(0);
		private final CrossReference cParametrosObjetoAngularCrossReference_21_0_0 = (CrossReference)cParametrosAssignment_21_0.eContents().get(0);
		private final RuleCall cParametrosObjetoAngularEStringParserRuleCall_21_0_0_1 = (RuleCall)cParametrosObjetoAngularCrossReference_21_0_0.eContents().get(1);
		private final Group cGroup_21_1 = (Group)cGroup_21.eContents().get(1);
		private final RuleCall cCOMATerminalRuleCall_21_1_0 = (RuleCall)cGroup_21_1.eContents().get(0);
		private final Assignment cParametrosAssignment_21_1_1 = (Assignment)cGroup_21_1.eContents().get(1);
		private final CrossReference cParametrosObjetoAngularCrossReference_21_1_1_0 = (CrossReference)cParametrosAssignment_21_1_1.eContents().get(0);
		private final RuleCall cParametrosObjetoAngularEStringParserRuleCall_21_1_1_0_1 = (RuleCall)cParametrosObjetoAngularCrossReference_21_1_1_0.eContents().get(1);
		private final RuleCall cCOMATerminalRuleCall_22 = (RuleCall)cGroup.eContents().get(22);
		private final Assignment cFuncionAssignment_23 = (Assignment)cGroup.eContents().get(23);
		private final RuleCall cFuncionFuncionParserRuleCall_23_0 = (RuleCall)cFuncionAssignment_23.eContents().get(0);
		private final RuleCall cPARENTESIS_CUADRADO_DERECHOTerminalRuleCall_24 = (RuleCall)cGroup.eContents().get(24);
		private final RuleCall cLLAVE_DERECHATerminalRuleCall_25 = (RuleCall)cGroup.eContents().get(25);
		private final RuleCall cPARENTESIS_DERECHOTerminalRuleCall_26 = (RuleCall)cGroup.eContents().get(26);
		private final RuleCall cPUNTO_Y_COMATerminalRuleCall_27 = (RuleCall)cGroup.eContents().get(27);
		
		//Componente:
		//	{Componente} (COMILLAS USE STRICT COMILLAS PUNTO_Y_COMA)?
		//	ANGULAR PUNTO
		//	MODULE PARENTESIS_IZQUIERDO modulo=[Modulo|EString] PARENTESIS_DERECHO PUNTO
		//	COMPONENT PARENTESIS_IZQUIERDO name=EString COMA
		//	LLAVE_IZQUIERDA
		//	TEMPLATE_URL DOS_PUNTOS template=[Template|EString] COMA
		//	CONTROLLER DOS_PUNTOS
		//	PARENTESIS_CUADRADO_IZQUIERDO (parametros+=[ObjetoAngular|EString] (COMA parametros+=[ObjetoAngular|EString])*)* COMA
		//	funcion=Funcion
		//	PARENTESIS_CUADRADO_DERECHO
		//	LLAVE_DERECHA PARENTESIS_DERECHO PUNTO_Y_COMA;
		@Override public ParserRule getRule() { return rule; }
		
		//{Componente} (COMILLAS USE STRICT COMILLAS PUNTO_Y_COMA)? ANGULAR PUNTO MODULE PARENTESIS_IZQUIERDO
		//modulo=[Modulo|EString] PARENTESIS_DERECHO PUNTO COMPONENT PARENTESIS_IZQUIERDO name=EString COMA LLAVE_IZQUIERDA
		//TEMPLATE_URL DOS_PUNTOS template=[Template|EString] COMA CONTROLLER DOS_PUNTOS PARENTESIS_CUADRADO_IZQUIERDO
		//(parametros+=[ObjetoAngular|EString] (COMA parametros+=[ObjetoAngular|EString])*)* COMA funcion=Funcion
		//PARENTESIS_CUADRADO_DERECHO LLAVE_DERECHA PARENTESIS_DERECHO PUNTO_Y_COMA
		public Group getGroup() { return cGroup; }
		
		//{Componente}
		public Action getComponenteAction_0() { return cComponenteAction_0; }
		
		//(COMILLAS USE STRICT COMILLAS PUNTO_Y_COMA)?
		public Group getGroup_1() { return cGroup_1; }
		
		//COMILLAS
		public RuleCall getCOMILLASTerminalRuleCall_1_0() { return cCOMILLASTerminalRuleCall_1_0; }
		
		//USE
		public RuleCall getUSETerminalRuleCall_1_1() { return cUSETerminalRuleCall_1_1; }
		
		//STRICT
		public RuleCall getSTRICTTerminalRuleCall_1_2() { return cSTRICTTerminalRuleCall_1_2; }
		
		//COMILLAS
		public RuleCall getCOMILLASTerminalRuleCall_1_3() { return cCOMILLASTerminalRuleCall_1_3; }
		
		//PUNTO_Y_COMA
		public RuleCall getPUNTO_Y_COMATerminalRuleCall_1_4() { return cPUNTO_Y_COMATerminalRuleCall_1_4; }
		
		//ANGULAR
		public RuleCall getANGULARTerminalRuleCall_2() { return cANGULARTerminalRuleCall_2; }
		
		//PUNTO
		public RuleCall getPUNTOTerminalRuleCall_3() { return cPUNTOTerminalRuleCall_3; }
		
		//MODULE
		public RuleCall getMODULETerminalRuleCall_4() { return cMODULETerminalRuleCall_4; }
		
		//PARENTESIS_IZQUIERDO
		public RuleCall getPARENTESIS_IZQUIERDOTerminalRuleCall_5() { return cPARENTESIS_IZQUIERDOTerminalRuleCall_5; }
		
		//modulo=[Modulo|EString]
		public Assignment getModuloAssignment_6() { return cModuloAssignment_6; }
		
		//[Modulo|EString]
		public CrossReference getModuloModuloCrossReference_6_0() { return cModuloModuloCrossReference_6_0; }
		
		//EString
		public RuleCall getModuloModuloEStringParserRuleCall_6_0_1() { return cModuloModuloEStringParserRuleCall_6_0_1; }
		
		//PARENTESIS_DERECHO
		public RuleCall getPARENTESIS_DERECHOTerminalRuleCall_7() { return cPARENTESIS_DERECHOTerminalRuleCall_7; }
		
		//PUNTO
		public RuleCall getPUNTOTerminalRuleCall_8() { return cPUNTOTerminalRuleCall_8; }
		
		//COMPONENT
		public RuleCall getCOMPONENTTerminalRuleCall_9() { return cCOMPONENTTerminalRuleCall_9; }
		
		//PARENTESIS_IZQUIERDO
		public RuleCall getPARENTESIS_IZQUIERDOTerminalRuleCall_10() { return cPARENTESIS_IZQUIERDOTerminalRuleCall_10; }
		
		//name=EString
		public Assignment getNameAssignment_11() { return cNameAssignment_11; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_11_0() { return cNameEStringParserRuleCall_11_0; }
		
		//COMA
		public RuleCall getCOMATerminalRuleCall_12() { return cCOMATerminalRuleCall_12; }
		
		//LLAVE_IZQUIERDA
		public RuleCall getLLAVE_IZQUIERDATerminalRuleCall_13() { return cLLAVE_IZQUIERDATerminalRuleCall_13; }
		
		//TEMPLATE_URL
		public RuleCall getTEMPLATE_URLTerminalRuleCall_14() { return cTEMPLATE_URLTerminalRuleCall_14; }
		
		//DOS_PUNTOS
		public RuleCall getDOS_PUNTOSTerminalRuleCall_15() { return cDOS_PUNTOSTerminalRuleCall_15; }
		
		//template=[Template|EString]
		public Assignment getTemplateAssignment_16() { return cTemplateAssignment_16; }
		
		//[Template|EString]
		public CrossReference getTemplateTemplateCrossReference_16_0() { return cTemplateTemplateCrossReference_16_0; }
		
		//EString
		public RuleCall getTemplateTemplateEStringParserRuleCall_16_0_1() { return cTemplateTemplateEStringParserRuleCall_16_0_1; }
		
		//COMA
		public RuleCall getCOMATerminalRuleCall_17() { return cCOMATerminalRuleCall_17; }
		
		//CONTROLLER
		public RuleCall getCONTROLLERTerminalRuleCall_18() { return cCONTROLLERTerminalRuleCall_18; }
		
		//DOS_PUNTOS
		public RuleCall getDOS_PUNTOSTerminalRuleCall_19() { return cDOS_PUNTOSTerminalRuleCall_19; }
		
		//PARENTESIS_CUADRADO_IZQUIERDO
		public RuleCall getPARENTESIS_CUADRADO_IZQUIERDOTerminalRuleCall_20() { return cPARENTESIS_CUADRADO_IZQUIERDOTerminalRuleCall_20; }
		
		//(parametros+=[ObjetoAngular|EString] (COMA parametros+=[ObjetoAngular|EString])*)*
		public Group getGroup_21() { return cGroup_21; }
		
		//parametros+=[ObjetoAngular|EString]
		public Assignment getParametrosAssignment_21_0() { return cParametrosAssignment_21_0; }
		
		//[ObjetoAngular|EString]
		public CrossReference getParametrosObjetoAngularCrossReference_21_0_0() { return cParametrosObjetoAngularCrossReference_21_0_0; }
		
		//EString
		public RuleCall getParametrosObjetoAngularEStringParserRuleCall_21_0_0_1() { return cParametrosObjetoAngularEStringParserRuleCall_21_0_0_1; }
		
		//(COMA parametros+=[ObjetoAngular|EString])*
		public Group getGroup_21_1() { return cGroup_21_1; }
		
		//COMA
		public RuleCall getCOMATerminalRuleCall_21_1_0() { return cCOMATerminalRuleCall_21_1_0; }
		
		//parametros+=[ObjetoAngular|EString]
		public Assignment getParametrosAssignment_21_1_1() { return cParametrosAssignment_21_1_1; }
		
		//[ObjetoAngular|EString]
		public CrossReference getParametrosObjetoAngularCrossReference_21_1_1_0() { return cParametrosObjetoAngularCrossReference_21_1_1_0; }
		
		//EString
		public RuleCall getParametrosObjetoAngularEStringParserRuleCall_21_1_1_0_1() { return cParametrosObjetoAngularEStringParserRuleCall_21_1_1_0_1; }
		
		//COMA
		public RuleCall getCOMATerminalRuleCall_22() { return cCOMATerminalRuleCall_22; }
		
		//funcion=Funcion
		public Assignment getFuncionAssignment_23() { return cFuncionAssignment_23; }
		
		//Funcion
		public RuleCall getFuncionFuncionParserRuleCall_23_0() { return cFuncionFuncionParserRuleCall_23_0; }
		
		//PARENTESIS_CUADRADO_DERECHO
		public RuleCall getPARENTESIS_CUADRADO_DERECHOTerminalRuleCall_24() { return cPARENTESIS_CUADRADO_DERECHOTerminalRuleCall_24; }
		
		//LLAVE_DERECHA
		public RuleCall getLLAVE_DERECHATerminalRuleCall_25() { return cLLAVE_DERECHATerminalRuleCall_25; }
		
		//PARENTESIS_DERECHO
		public RuleCall getPARENTESIS_DERECHOTerminalRuleCall_26() { return cPARENTESIS_DERECHOTerminalRuleCall_26; }
		
		//PUNTO_Y_COMA
		public RuleCall getPUNTO_Y_COMATerminalRuleCall_27() { return cPUNTO_Y_COMATerminalRuleCall_27; }
	}
	public class FuncionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.uniandes.angular.AngularDsl.Funcion");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cFuncionAction_0 = (Action)cGroup.eContents().get(0);
		private final RuleCall cFUNCTIONTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final RuleCall cPARENTESIS_IZQUIERDOTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final Assignment cParametrosAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cParametrosEStringParserRuleCall_4_0 = (RuleCall)cParametrosAssignment_4.eContents().get(0);
		private final RuleCall cPARENTESIS_DERECHOTerminalRuleCall_5 = (RuleCall)cGroup.eContents().get(5);
		private final RuleCall cLLAVE_IZQUIERDATerminalRuleCall_6 = (RuleCall)cGroup.eContents().get(6);
		private final Assignment cVariablesAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cVariablesVariableParserRuleCall_7_0 = (RuleCall)cVariablesAssignment_7.eContents().get(0);
		private final Assignment cBodyAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cBodyEStringParserRuleCall_8_0 = (RuleCall)cBodyAssignment_8.eContents().get(0);
		private final RuleCall cLLAVE_DERECHATerminalRuleCall_9 = (RuleCall)cGroup.eContents().get(9);
		
		//Funcion:
		//	{Funcion} FUNCTION name=EString PARENTESIS_IZQUIERDO parametros=EString PARENTESIS_DERECHO LLAVE_IZQUIERDA
		//	variables+=Variable* body=EString LLAVE_DERECHA;
		@Override public ParserRule getRule() { return rule; }
		
		//{Funcion} FUNCTION name=EString PARENTESIS_IZQUIERDO parametros=EString PARENTESIS_DERECHO LLAVE_IZQUIERDA
		//variables+=Variable* body=EString LLAVE_DERECHA
		public Group getGroup() { return cGroup; }
		
		//{Funcion}
		public Action getFuncionAction_0() { return cFuncionAction_0; }
		
		//FUNCTION
		public RuleCall getFUNCTIONTerminalRuleCall_1() { return cFUNCTIONTerminalRuleCall_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//PARENTESIS_IZQUIERDO
		public RuleCall getPARENTESIS_IZQUIERDOTerminalRuleCall_3() { return cPARENTESIS_IZQUIERDOTerminalRuleCall_3; }
		
		//parametros=EString
		public Assignment getParametrosAssignment_4() { return cParametrosAssignment_4; }
		
		//EString
		public RuleCall getParametrosEStringParserRuleCall_4_0() { return cParametrosEStringParserRuleCall_4_0; }
		
		//PARENTESIS_DERECHO
		public RuleCall getPARENTESIS_DERECHOTerminalRuleCall_5() { return cPARENTESIS_DERECHOTerminalRuleCall_5; }
		
		//LLAVE_IZQUIERDA
		public RuleCall getLLAVE_IZQUIERDATerminalRuleCall_6() { return cLLAVE_IZQUIERDATerminalRuleCall_6; }
		
		//variables+=Variable*
		public Assignment getVariablesAssignment_7() { return cVariablesAssignment_7; }
		
		//Variable
		public RuleCall getVariablesVariableParserRuleCall_7_0() { return cVariablesVariableParserRuleCall_7_0; }
		
		//body=EString
		public Assignment getBodyAssignment_8() { return cBodyAssignment_8; }
		
		//EString
		public RuleCall getBodyEStringParserRuleCall_8_0() { return cBodyEStringParserRuleCall_8_0; }
		
		//LLAVE_DERECHA
		public RuleCall getLLAVE_DERECHATerminalRuleCall_9() { return cLLAVE_DERECHATerminalRuleCall_9; }
	}
	public class VariableElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.uniandes.angular.AngularDsl.Variable");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cVariableAction_0 = (Action)cGroup.eContents().get(0);
		private final RuleCall cVARTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final RuleCall cIGUALTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final Assignment cValorAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cValorEStringParserRuleCall_4_0 = (RuleCall)cValorAssignment_4.eContents().get(0);
		private final RuleCall cPUNTO_Y_COMATerminalRuleCall_5 = (RuleCall)cGroup.eContents().get(5);
		
		//Variable:
		//	{Variable} VAR name=EString IGUAL valor=EString PUNTO_Y_COMA;
		@Override public ParserRule getRule() { return rule; }
		
		//{Variable} VAR name=EString IGUAL valor=EString PUNTO_Y_COMA
		public Group getGroup() { return cGroup; }
		
		//{Variable}
		public Action getVariableAction_0() { return cVariableAction_0; }
		
		//VAR
		public RuleCall getVARTerminalRuleCall_1() { return cVARTerminalRuleCall_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//IGUAL
		public RuleCall getIGUALTerminalRuleCall_3() { return cIGUALTerminalRuleCall_3; }
		
		//valor=EString
		public Assignment getValorAssignment_4() { return cValorAssignment_4; }
		
		//EString
		public RuleCall getValorEStringParserRuleCall_4_0() { return cValorEStringParserRuleCall_4_0; }
		
		//PUNTO_Y_COMA
		public RuleCall getPUNTO_Y_COMATerminalRuleCall_5() { return cPUNTO_Y_COMATerminalRuleCall_5; }
	}
	public class TemplateElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.uniandes.angular.AngularDsl.Template");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cTemplateAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cAsteriskKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cSentenciashtmlAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cSentenciashtmlSentenciaHTMLParserRuleCall_3_0 = (RuleCall)cSentenciashtmlAssignment_3.eContents().get(0);
		
		//Template:
		//	{Template} name=EString '*' sentenciashtml+=SentenciaHTML*;
		@Override public ParserRule getRule() { return rule; }
		
		//{Template} name=EString '*' sentenciashtml+=SentenciaHTML*
		public Group getGroup() { return cGroup; }
		
		//{Template}
		public Action getTemplateAction_0() { return cTemplateAction_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'*'
		public Keyword getAsteriskKeyword_2() { return cAsteriskKeyword_2; }
		
		//sentenciashtml+=SentenciaHTML*
		public Assignment getSentenciashtmlAssignment_3() { return cSentenciashtmlAssignment_3; }
		
		//SentenciaHTML
		public RuleCall getSentenciashtmlSentenciaHTMLParserRuleCall_3_0() { return cSentenciashtmlSentenciaHTMLParserRuleCall_3_0; }
	}
	public class SentenciaHTMLElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.uniandes.angular.AngularDsl.SentenciaHTML");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cSentenciaHTMLAction_0 = (Action)cGroup.eContents().get(0);
		private final RuleCall cMENOR_QUETerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Assignment cPropiedadesAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cPropiedadesPropiedadParserRuleCall_3_0 = (RuleCall)cPropiedadesAssignment_3.eContents().get(0);
		private final Assignment cDirectivasAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cDirectivasDirectivaParserRuleCall_4_0 = (RuleCall)cDirectivasAssignment_4.eContents().get(0);
		private final RuleCall cSLASHTerminalRuleCall_5 = (RuleCall)cGroup.eContents().get(5);
		private final RuleCall cMAYOR_QUETerminalRuleCall_6 = (RuleCall)cGroup.eContents().get(6);
		private final Assignment cCurlybracesAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cCurlybracesCurlyBracesParserRuleCall_7_0 = (RuleCall)cCurlybracesAssignment_7.eContents().get(0);
		private final Assignment cSentenciashtmlAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final CrossReference cSentenciashtmlSentenciaHTMLCrossReference_8_0 = (CrossReference)cSentenciashtmlAssignment_8.eContents().get(0);
		private final RuleCall cSentenciashtmlSentenciaHTMLEStringParserRuleCall_8_0_1 = (RuleCall)cSentenciashtmlSentenciaHTMLCrossReference_8_0.eContents().get(1);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final RuleCall cMENOR_QUETerminalRuleCall_9_0 = (RuleCall)cGroup_9.eContents().get(0);
		private final RuleCall cSLASHTerminalRuleCall_9_1 = (RuleCall)cGroup_9.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_9_2 = (RuleCall)cGroup_9.eContents().get(2);
		private final RuleCall cMAYOR_QUETerminalRuleCall_9_3 = (RuleCall)cGroup_9.eContents().get(3);
		
		//SentenciaHTML:
		//	{SentenciaHTML} MENOR_QUE name=EString propiedades+=Propiedad* directivas+=Directiva* SLASH* MAYOR_QUE
		//	curlybraces+=CurlyBraces*
		//	sentenciashtml+=[SentenciaHTML|EString]* (MENOR_QUE SLASH STRING MAYOR_QUE)?;
		@Override public ParserRule getRule() { return rule; }
		
		//{SentenciaHTML} MENOR_QUE name=EString propiedades+=Propiedad* directivas+=Directiva* SLASH* MAYOR_QUE
		//curlybraces+=CurlyBraces* sentenciashtml+=[SentenciaHTML|EString]* (MENOR_QUE SLASH STRING MAYOR_QUE)?
		public Group getGroup() { return cGroup; }
		
		//{SentenciaHTML}
		public Action getSentenciaHTMLAction_0() { return cSentenciaHTMLAction_0; }
		
		//MENOR_QUE
		public RuleCall getMENOR_QUETerminalRuleCall_1() { return cMENOR_QUETerminalRuleCall_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//propiedades+=Propiedad*
		public Assignment getPropiedadesAssignment_3() { return cPropiedadesAssignment_3; }
		
		//Propiedad
		public RuleCall getPropiedadesPropiedadParserRuleCall_3_0() { return cPropiedadesPropiedadParserRuleCall_3_0; }
		
		//directivas+=Directiva*
		public Assignment getDirectivasAssignment_4() { return cDirectivasAssignment_4; }
		
		//Directiva
		public RuleCall getDirectivasDirectivaParserRuleCall_4_0() { return cDirectivasDirectivaParserRuleCall_4_0; }
		
		//SLASH*
		public RuleCall getSLASHTerminalRuleCall_5() { return cSLASHTerminalRuleCall_5; }
		
		//MAYOR_QUE
		public RuleCall getMAYOR_QUETerminalRuleCall_6() { return cMAYOR_QUETerminalRuleCall_6; }
		
		//curlybraces+=CurlyBraces*
		public Assignment getCurlybracesAssignment_7() { return cCurlybracesAssignment_7; }
		
		//CurlyBraces
		public RuleCall getCurlybracesCurlyBracesParserRuleCall_7_0() { return cCurlybracesCurlyBracesParserRuleCall_7_0; }
		
		//sentenciashtml+=[SentenciaHTML|EString]*
		public Assignment getSentenciashtmlAssignment_8() { return cSentenciashtmlAssignment_8; }
		
		//[SentenciaHTML|EString]
		public CrossReference getSentenciashtmlSentenciaHTMLCrossReference_8_0() { return cSentenciashtmlSentenciaHTMLCrossReference_8_0; }
		
		//EString
		public RuleCall getSentenciashtmlSentenciaHTMLEStringParserRuleCall_8_0_1() { return cSentenciashtmlSentenciaHTMLEStringParserRuleCall_8_0_1; }
		
		//(MENOR_QUE SLASH STRING MAYOR_QUE)?
		public Group getGroup_9() { return cGroup_9; }
		
		//MENOR_QUE
		public RuleCall getMENOR_QUETerminalRuleCall_9_0() { return cMENOR_QUETerminalRuleCall_9_0; }
		
		//SLASH
		public RuleCall getSLASHTerminalRuleCall_9_1() { return cSLASHTerminalRuleCall_9_1; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_9_2() { return cSTRINGTerminalRuleCall_9_2; }
		
		//MAYOR_QUE
		public RuleCall getMAYOR_QUETerminalRuleCall_9_3() { return cMAYOR_QUETerminalRuleCall_9_3; }
	}
	public class DirectivaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.uniandes.angular.AngularDsl.Directiva");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cDirectivaAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cNgKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final RuleCall cIGUALTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final Assignment cCurlybracesAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cCurlybracesCurlyBracesCrossReference_4_0 = (CrossReference)cCurlybracesAssignment_4.eContents().get(0);
		private final RuleCall cCurlybracesCurlyBracesEStringParserRuleCall_4_0_1 = (RuleCall)cCurlybracesCurlyBracesCrossReference_4_0.eContents().get(1);
		private final Assignment cReferenciaAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final CrossReference cReferenciaObjetoAngularCrossReference_5_0 = (CrossReference)cReferenciaAssignment_5.eContents().get(0);
		private final RuleCall cReferenciaObjetoAngularEStringParserRuleCall_5_0_1 = (RuleCall)cReferenciaObjetoAngularCrossReference_5_0.eContents().get(1);
		
		//Directiva:
		//	{Directiva}
		//	'ng-' name=EString IGUAL curlybraces=[CurlyBraces|EString]? referencia=[ObjetoAngular|EString];
		@Override public ParserRule getRule() { return rule; }
		
		//{Directiva} 'ng-' name=EString IGUAL curlybraces=[CurlyBraces|EString]? referencia=[ObjetoAngular|EString]
		public Group getGroup() { return cGroup; }
		
		//{Directiva}
		public Action getDirectivaAction_0() { return cDirectivaAction_0; }
		
		//'ng-'
		public Keyword getNgKeyword_1() { return cNgKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//IGUAL
		public RuleCall getIGUALTerminalRuleCall_3() { return cIGUALTerminalRuleCall_3; }
		
		//curlybraces=[CurlyBraces|EString]?
		public Assignment getCurlybracesAssignment_4() { return cCurlybracesAssignment_4; }
		
		//[CurlyBraces|EString]
		public CrossReference getCurlybracesCurlyBracesCrossReference_4_0() { return cCurlybracesCurlyBracesCrossReference_4_0; }
		
		//EString
		public RuleCall getCurlybracesCurlyBracesEStringParserRuleCall_4_0_1() { return cCurlybracesCurlyBracesEStringParserRuleCall_4_0_1; }
		
		//referencia=[ObjetoAngular|EString]
		public Assignment getReferenciaAssignment_5() { return cReferenciaAssignment_5; }
		
		//[ObjetoAngular|EString]
		public CrossReference getReferenciaObjetoAngularCrossReference_5_0() { return cReferenciaObjetoAngularCrossReference_5_0; }
		
		//EString
		public RuleCall getReferenciaObjetoAngularEStringParserRuleCall_5_0_1() { return cReferenciaObjetoAngularEStringParserRuleCall_5_0_1; }
	}
	public class PropiedadElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.uniandes.angular.AngularDsl.Propiedad");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cPropiedadAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final RuleCall cIGUALTerminalRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		private final RuleCall cSTRINGTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		
		//Propiedad:
		//	{Propiedad} name=EString IGUAL STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//{Propiedad} name=EString IGUAL STRING
		public Group getGroup() { return cGroup; }
		
		//{Propiedad}
		public Action getPropiedadAction_0() { return cPropiedadAction_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//IGUAL
		public RuleCall getIGUALTerminalRuleCall_2() { return cIGUALTerminalRuleCall_2; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_3() { return cSTRINGTerminalRuleCall_3; }
	}
	public class CurlyBracesElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.uniandes.angular.AngularDsl.CurlyBraces");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cDOBLE_LLAVE_IZQUIERDATerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Keyword cDollarSignKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cExpresionAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cExpresionExpresionParserRuleCall_2_0 = (RuleCall)cExpresionAssignment_2.eContents().get(0);
		private final Assignment cFiltroAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cFiltroFiltroParserRuleCall_3_0 = (RuleCall)cFiltroAssignment_3.eContents().get(0);
		private final RuleCall cDOBLE_LLAVE_DERECHATerminalRuleCall_4 = (RuleCall)cGroup.eContents().get(4);
		
		//CurlyBraces:
		//	DOBLE_LLAVE_IZQUIERDA '$'? expresion=Expresion filtro=Filtro? DOBLE_LLAVE_DERECHA;
		@Override public ParserRule getRule() { return rule; }
		
		//DOBLE_LLAVE_IZQUIERDA '$'? expresion=Expresion filtro=Filtro? DOBLE_LLAVE_DERECHA
		public Group getGroup() { return cGroup; }
		
		//DOBLE_LLAVE_IZQUIERDA
		public RuleCall getDOBLE_LLAVE_IZQUIERDATerminalRuleCall_0() { return cDOBLE_LLAVE_IZQUIERDATerminalRuleCall_0; }
		
		//'$'?
		public Keyword getDollarSignKeyword_1() { return cDollarSignKeyword_1; }
		
		//expresion=Expresion
		public Assignment getExpresionAssignment_2() { return cExpresionAssignment_2; }
		
		//Expresion
		public RuleCall getExpresionExpresionParserRuleCall_2_0() { return cExpresionExpresionParserRuleCall_2_0; }
		
		//filtro=Filtro?
		public Assignment getFiltroAssignment_3() { return cFiltroAssignment_3; }
		
		//Filtro
		public RuleCall getFiltroFiltroParserRuleCall_3_0() { return cFiltroFiltroParserRuleCall_3_0; }
		
		//DOBLE_LLAVE_DERECHA
		public RuleCall getDOBLE_LLAVE_DERECHATerminalRuleCall_4() { return cDOBLE_LLAVE_DERECHATerminalRuleCall_4; }
	}
	public class ExpresionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.uniandes.angular.AngularDsl.Expresion");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cExpresionAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cValorAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cValorEStringParserRuleCall_1_0 = (RuleCall)cValorAssignment_1.eContents().get(0);
		private final Assignment cReferenciaAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final CrossReference cReferenciaObjetoAngularCrossReference_2_0 = (CrossReference)cReferenciaAssignment_2.eContents().get(0);
		private final RuleCall cReferenciaObjetoAngularEStringParserRuleCall_2_0_1 = (RuleCall)cReferenciaObjetoAngularCrossReference_2_0.eContents().get(1);
		
		//Expresion:
		//	{Expresion} valor=EString
		//	referencia=[ObjetoAngular|EString];
		@Override public ParserRule getRule() { return rule; }
		
		//{Expresion} valor=EString referencia=[ObjetoAngular|EString]
		public Group getGroup() { return cGroup; }
		
		//{Expresion}
		public Action getExpresionAction_0() { return cExpresionAction_0; }
		
		//valor=EString
		public Assignment getValorAssignment_1() { return cValorAssignment_1; }
		
		//EString
		public RuleCall getValorEStringParserRuleCall_1_0() { return cValorEStringParserRuleCall_1_0; }
		
		//referencia=[ObjetoAngular|EString]
		public Assignment getReferenciaAssignment_2() { return cReferenciaAssignment_2; }
		
		//[ObjetoAngular|EString]
		public CrossReference getReferenciaObjetoAngularCrossReference_2_0() { return cReferenciaObjetoAngularCrossReference_2_0; }
		
		//EString
		public RuleCall getReferenciaObjetoAngularEStringParserRuleCall_2_0_1() { return cReferenciaObjetoAngularEStringParserRuleCall_2_0_1; }
	}
	public class FiltroElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.uniandes.angular.AngularDsl.Filtro");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cFiltroAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cVerticalLineKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cParametrosAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cParametrosEStringParserRuleCall_2_0 = (RuleCall)cParametrosAssignment_2.eContents().get(0);
		
		//Filtro:
		//	{Filtro}
		//	'|' parametros=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//{Filtro} '|' parametros=EString
		public Group getGroup() { return cGroup; }
		
		//{Filtro}
		public Action getFiltroAction_0() { return cFiltroAction_0; }
		
		//'|'
		public Keyword getVerticalLineKeyword_1() { return cVerticalLineKeyword_1; }
		
		//parametros=EString
		public Assignment getParametrosAssignment_2() { return cParametrosAssignment_2; }
		
		//EString
		public RuleCall getParametrosEStringParserRuleCall_2_0() { return cParametrosEStringParserRuleCall_2_0; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.uniandes.angular.AngularDsl.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString:
		//	STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class EBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.uniandes.angular.AngularDsl.EBoolean");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//EBoolean ecore::EBoolean:
		//	'true' | 'false';
		@Override public ParserRule getRule() { return rule; }
		
		//'true' | 'false'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'true'
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }
		
		//'false'
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}
	
	
	private final AppAngularElements pAppAngular;
	private final ObjetoAngularElements pObjetoAngular;
	private final ModuloElements pModulo;
	private final ServiceElements pService;
	private final ComponenteElements pComponente;
	private final FuncionElements pFuncion;
	private final VariableElements pVariable;
	private final TemplateElements pTemplate;
	private final SentenciaHTMLElements pSentenciaHTML;
	private final DirectivaElements pDirectiva;
	private final PropiedadElements pPropiedad;
	private final CurlyBracesElements pCurlyBraces;
	private final ExpresionElements pExpresion;
	private final FiltroElements pFiltro;
	private final EStringElements pEString;
	private final EBooleanElements pEBoolean;
	private final TerminalRule tUSE;
	private final TerminalRule tSTRICT;
	private final TerminalRule tCOMILLAS;
	private final TerminalRule tPUNTO_Y_COMA;
	private final TerminalRule tPUNTO;
	private final TerminalRule tCOMA;
	private final TerminalRule tDOS_PUNTOS;
	private final TerminalRule tANGULAR;
	private final TerminalRule tMODULE;
	private final TerminalRule tPARENTESIS_IZQUIERDO;
	private final TerminalRule tPARENTESIS_DERECHO;
	private final TerminalRule tCOMPONENT;
	private final TerminalRule tLLAVE_IZQUIERDA;
	private final TerminalRule tLLAVE_DERECHA;
	private final TerminalRule tTEMPLATE_URL;
	private final TerminalRule tCONTROLLER;
	private final TerminalRule tPARENTESIS_CUADRADO_IZQUIERDO;
	private final TerminalRule tPARENTESIS_CUADRADO_DERECHO;
	private final TerminalRule tFUNCTION;
	private final TerminalRule tVAR;
	private final TerminalRule tIGUAL;
	private final TerminalRule tMENOR_QUE;
	private final TerminalRule tMAYOR_QUE;
	private final TerminalRule tSLASH;
	private final TerminalRule tDOBLE_LLAVE_IZQUIERDA;
	private final TerminalRule tDOBLE_LLAVE_DERECHA;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public AngularDslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pAppAngular = new AppAngularElements();
		this.pObjetoAngular = new ObjetoAngularElements();
		this.pModulo = new ModuloElements();
		this.pService = new ServiceElements();
		this.pComponente = new ComponenteElements();
		this.pFuncion = new FuncionElements();
		this.pVariable = new VariableElements();
		this.pTemplate = new TemplateElements();
		this.pSentenciaHTML = new SentenciaHTMLElements();
		this.pDirectiva = new DirectivaElements();
		this.pPropiedad = new PropiedadElements();
		this.pCurlyBraces = new CurlyBracesElements();
		this.pExpresion = new ExpresionElements();
		this.pFiltro = new FiltroElements();
		this.pEString = new EStringElements();
		this.pEBoolean = new EBooleanElements();
		this.tUSE = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.uniandes.angular.AngularDsl.USE");
		this.tSTRICT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.uniandes.angular.AngularDsl.STRICT");
		this.tCOMILLAS = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.uniandes.angular.AngularDsl.COMILLAS");
		this.tPUNTO_Y_COMA = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.uniandes.angular.AngularDsl.PUNTO_Y_COMA");
		this.tPUNTO = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.uniandes.angular.AngularDsl.PUNTO");
		this.tCOMA = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.uniandes.angular.AngularDsl.COMA");
		this.tDOS_PUNTOS = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.uniandes.angular.AngularDsl.DOS_PUNTOS");
		this.tANGULAR = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.uniandes.angular.AngularDsl.ANGULAR");
		this.tMODULE = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.uniandes.angular.AngularDsl.MODULE");
		this.tPARENTESIS_IZQUIERDO = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.uniandes.angular.AngularDsl.PARENTESIS_IZQUIERDO");
		this.tPARENTESIS_DERECHO = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.uniandes.angular.AngularDsl.PARENTESIS_DERECHO");
		this.tCOMPONENT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.uniandes.angular.AngularDsl.COMPONENT");
		this.tLLAVE_IZQUIERDA = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.uniandes.angular.AngularDsl.LLAVE_IZQUIERDA");
		this.tLLAVE_DERECHA = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.uniandes.angular.AngularDsl.LLAVE_DERECHA");
		this.tTEMPLATE_URL = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.uniandes.angular.AngularDsl.TEMPLATE_URL");
		this.tCONTROLLER = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.uniandes.angular.AngularDsl.CONTROLLER");
		this.tPARENTESIS_CUADRADO_IZQUIERDO = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.uniandes.angular.AngularDsl.PARENTESIS_CUADRADO_IZQUIERDO");
		this.tPARENTESIS_CUADRADO_DERECHO = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.uniandes.angular.AngularDsl.PARENTESIS_CUADRADO_DERECHO");
		this.tFUNCTION = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.uniandes.angular.AngularDsl.FUNCTION");
		this.tVAR = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.uniandes.angular.AngularDsl.VAR");
		this.tIGUAL = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.uniandes.angular.AngularDsl.IGUAL");
		this.tMENOR_QUE = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.uniandes.angular.AngularDsl.MENOR_QUE");
		this.tMAYOR_QUE = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.uniandes.angular.AngularDsl.MAYOR_QUE");
		this.tSLASH = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.uniandes.angular.AngularDsl.SLASH");
		this.tDOBLE_LLAVE_IZQUIERDA = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.uniandes.angular.AngularDsl.DOBLE_LLAVE_IZQUIERDA");
		this.tDOBLE_LLAVE_DERECHA = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.uniandes.angular.AngularDsl.DOBLE_LLAVE_DERECHA");
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("co.edu.uniandes.angular.AngularDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//AppAngular:
	//	modulos+=Modulo | componentes+=Componente | services+=Service | templates+=Template;
	public AppAngularElements getAppAngularAccess() {
		return pAppAngular;
	}
	
	public ParserRule getAppAngularRule() {
		return getAppAngularAccess().getRule();
	}
	
	//ObjetoAngular:
	//	Modulo | Componente | Service;
	public ObjetoAngularElements getObjetoAngularAccess() {
		return pObjetoAngular;
	}
	
	public ParserRule getObjetoAngularRule() {
		return getObjetoAngularAccess().getRule();
	}
	
	//Modulo:
	//	{Modulo} (COMILLAS USE STRICT COMILLAS PUNTO_Y_COMA)? ANGULAR PUNTO MODULE PARENTESIS_IZQUIERDO
	//	name=EString COMA
	//	PARENTESIS_CUADRADO_IZQUIERDO (parametros+=[ObjetoAngular|EString] (COMA parametros+=[ObjetoAngular|EString])*)*
	//	PARENTESIS_CUADRADO_DERECHO
	//	PARENTESIS_DERECHO PUNTO_Y_COMA;
	public ModuloElements getModuloAccess() {
		return pModulo;
	}
	
	public ParserRule getModuloRule() {
		return getModuloAccess().getRule();
	}
	
	//Service:
	//	{Service} (COMILLAS USE STRICT COMILLAS PUNTO_Y_COMA)? ANGULAR PUNTO MODULE PARENTESIS_IZQUIERDO
	//	modulo=[Modulo|EString] PARENTESIS_DERECHO PUNTO 'factory' PARENTESIS_IZQUIERDO name=EString COMA
	//	PARENTESIS_CUADRADO_IZQUIERDO (parametros+=[ObjetoAngular|EString] (COMA parametros+=[ObjetoAngular|EString])*)* COMA
	//	funcion=Funcion
	//	PARENTESIS_CUADRADO_DERECHO
	//	PARENTESIS_DERECHO PUNTO_Y_COMA;
	public ServiceElements getServiceAccess() {
		return pService;
	}
	
	public ParserRule getServiceRule() {
		return getServiceAccess().getRule();
	}
	
	//Componente:
	//	{Componente} (COMILLAS USE STRICT COMILLAS PUNTO_Y_COMA)?
	//	ANGULAR PUNTO
	//	MODULE PARENTESIS_IZQUIERDO modulo=[Modulo|EString] PARENTESIS_DERECHO PUNTO
	//	COMPONENT PARENTESIS_IZQUIERDO name=EString COMA
	//	LLAVE_IZQUIERDA
	//	TEMPLATE_URL DOS_PUNTOS template=[Template|EString] COMA
	//	CONTROLLER DOS_PUNTOS
	//	PARENTESIS_CUADRADO_IZQUIERDO (parametros+=[ObjetoAngular|EString] (COMA parametros+=[ObjetoAngular|EString])*)* COMA
	//	funcion=Funcion
	//	PARENTESIS_CUADRADO_DERECHO
	//	LLAVE_DERECHA PARENTESIS_DERECHO PUNTO_Y_COMA;
	public ComponenteElements getComponenteAccess() {
		return pComponente;
	}
	
	public ParserRule getComponenteRule() {
		return getComponenteAccess().getRule();
	}
	
	//Funcion:
	//	{Funcion} FUNCTION name=EString PARENTESIS_IZQUIERDO parametros=EString PARENTESIS_DERECHO LLAVE_IZQUIERDA
	//	variables+=Variable* body=EString LLAVE_DERECHA;
	public FuncionElements getFuncionAccess() {
		return pFuncion;
	}
	
	public ParserRule getFuncionRule() {
		return getFuncionAccess().getRule();
	}
	
	//Variable:
	//	{Variable} VAR name=EString IGUAL valor=EString PUNTO_Y_COMA;
	public VariableElements getVariableAccess() {
		return pVariable;
	}
	
	public ParserRule getVariableRule() {
		return getVariableAccess().getRule();
	}
	
	//Template:
	//	{Template} name=EString '*' sentenciashtml+=SentenciaHTML*;
	public TemplateElements getTemplateAccess() {
		return pTemplate;
	}
	
	public ParserRule getTemplateRule() {
		return getTemplateAccess().getRule();
	}
	
	//SentenciaHTML:
	//	{SentenciaHTML} MENOR_QUE name=EString propiedades+=Propiedad* directivas+=Directiva* SLASH* MAYOR_QUE
	//	curlybraces+=CurlyBraces*
	//	sentenciashtml+=[SentenciaHTML|EString]* (MENOR_QUE SLASH STRING MAYOR_QUE)?;
	public SentenciaHTMLElements getSentenciaHTMLAccess() {
		return pSentenciaHTML;
	}
	
	public ParserRule getSentenciaHTMLRule() {
		return getSentenciaHTMLAccess().getRule();
	}
	
	//Directiva:
	//	{Directiva}
	//	'ng-' name=EString IGUAL curlybraces=[CurlyBraces|EString]? referencia=[ObjetoAngular|EString];
	public DirectivaElements getDirectivaAccess() {
		return pDirectiva;
	}
	
	public ParserRule getDirectivaRule() {
		return getDirectivaAccess().getRule();
	}
	
	//Propiedad:
	//	{Propiedad} name=EString IGUAL STRING;
	public PropiedadElements getPropiedadAccess() {
		return pPropiedad;
	}
	
	public ParserRule getPropiedadRule() {
		return getPropiedadAccess().getRule();
	}
	
	//CurlyBraces:
	//	DOBLE_LLAVE_IZQUIERDA '$'? expresion=Expresion filtro=Filtro? DOBLE_LLAVE_DERECHA;
	public CurlyBracesElements getCurlyBracesAccess() {
		return pCurlyBraces;
	}
	
	public ParserRule getCurlyBracesRule() {
		return getCurlyBracesAccess().getRule();
	}
	
	//Expresion:
	//	{Expresion} valor=EString
	//	referencia=[ObjetoAngular|EString];
	public ExpresionElements getExpresionAccess() {
		return pExpresion;
	}
	
	public ParserRule getExpresionRule() {
		return getExpresionAccess().getRule();
	}
	
	//Filtro:
	//	{Filtro}
	//	'|' parametros=EString;
	public FiltroElements getFiltroAccess() {
		return pFiltro;
	}
	
	public ParserRule getFiltroRule() {
		return getFiltroAccess().getRule();
	}
	
	//EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//EBoolean ecore::EBoolean:
	//	'true' | 'false';
	public EBooleanElements getEBooleanAccess() {
		return pEBoolean;
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}
	
	//terminal USE:
	//	'use';
	public TerminalRule getUSERule() {
		return tUSE;
	}
	
	//terminal STRICT:
	//	'strict';
	public TerminalRule getSTRICTRule() {
		return tSTRICT;
	}
	
	//terminal COMILLAS:
	//	'\'';
	public TerminalRule getCOMILLASRule() {
		return tCOMILLAS;
	}
	
	//terminal PUNTO_Y_COMA:
	//	';';
	public TerminalRule getPUNTO_Y_COMARule() {
		return tPUNTO_Y_COMA;
	}
	
	//terminal PUNTO:
	//	'.';
	public TerminalRule getPUNTORule() {
		return tPUNTO;
	}
	
	//terminal COMA:
	//	',';
	public TerminalRule getCOMARule() {
		return tCOMA;
	}
	
	//terminal DOS_PUNTOS:
	//	':';
	public TerminalRule getDOS_PUNTOSRule() {
		return tDOS_PUNTOS;
	}
	
	//terminal ANGULAR:
	//	'angular';
	public TerminalRule getANGULARRule() {
		return tANGULAR;
	}
	
	//terminal MODULE:
	//	'module';
	public TerminalRule getMODULERule() {
		return tMODULE;
	}
	
	//terminal PARENTESIS_IZQUIERDO:
	//	'(';
	public TerminalRule getPARENTESIS_IZQUIERDORule() {
		return tPARENTESIS_IZQUIERDO;
	}
	
	//terminal PARENTESIS_DERECHO:
	//	')';
	public TerminalRule getPARENTESIS_DERECHORule() {
		return tPARENTESIS_DERECHO;
	}
	
	//terminal COMPONENT:
	//	'component';
	public TerminalRule getCOMPONENTRule() {
		return tCOMPONENT;
	}
	
	//terminal LLAVE_IZQUIERDA:
	//	'{';
	public TerminalRule getLLAVE_IZQUIERDARule() {
		return tLLAVE_IZQUIERDA;
	}
	
	//terminal LLAVE_DERECHA:
	//	'}';
	public TerminalRule getLLAVE_DERECHARule() {
		return tLLAVE_DERECHA;
	}
	
	//terminal TEMPLATE_URL:
	//	'templateUrl';
	public TerminalRule getTEMPLATE_URLRule() {
		return tTEMPLATE_URL;
	}
	
	//terminal CONTROLLER:
	//	'controller';
	public TerminalRule getCONTROLLERRule() {
		return tCONTROLLER;
	}
	
	//terminal PARENTESIS_CUADRADO_IZQUIERDO:
	//	'[';
	public TerminalRule getPARENTESIS_CUADRADO_IZQUIERDORule() {
		return tPARENTESIS_CUADRADO_IZQUIERDO;
	}
	
	//terminal PARENTESIS_CUADRADO_DERECHO:
	//	']';
	public TerminalRule getPARENTESIS_CUADRADO_DERECHORule() {
		return tPARENTESIS_CUADRADO_DERECHO;
	}
	
	//terminal FUNCTION:
	//	'function';
	public TerminalRule getFUNCTIONRule() {
		return tFUNCTION;
	}
	
	//terminal VAR:
	//	'var';
	public TerminalRule getVARRule() {
		return tVAR;
	}
	
	//terminal IGUAL:
	//	'=';
	public TerminalRule getIGUALRule() {
		return tIGUAL;
	}
	
	//terminal MENOR_QUE:
	//	'<';
	public TerminalRule getMENOR_QUERule() {
		return tMENOR_QUE;
	}
	
	//terminal MAYOR_QUE:
	//	'>';
	public TerminalRule getMAYOR_QUERule() {
		return tMAYOR_QUE;
	}
	
	//terminal SLASH:
	//	"/";
	public TerminalRule getSLASHRule() {
		return tSLASH;
	}
	
	//terminal DOBLE_LLAVE_IZQUIERDA:
	//	"{{";
	public TerminalRule getDOBLE_LLAVE_IZQUIERDARule() {
		return tDOBLE_LLAVE_IZQUIERDA;
	}
	
	//terminal DOBLE_LLAVE_DERECHA:
	//	"}}";
	public TerminalRule getDOBLE_LLAVE_DERECHARule() {
		return tDOBLE_LLAVE_DERECHA;
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
