/**
 * generated by Xtext 2.12.0
 */
package co.edu.uniandes.angular.ui.contentassist;

import co.edu.uniandes.angular.ui.contentassist.AbstractAngularDslProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class AngularDslProposalProvider extends AbstractAngularDslProposalProvider {
}
