/*
 * generated by Xtext 2.12.0
 */
package co.edu.uniandes.angular.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractAngularDslScopeProvider extends DelegatingScopeProvider {
}
